/*
 * ErGUI.java
 *
 * Created on 6 de Setembro de 2007, 08:31
 */
package br.uem.din.yandre.sctmf.view.modelos_formais.ling_regul.er;

import br.uem.din.yandre.sctmf.model.pojo.ER;
import br.uem.din.yandre.sctmf.model.pojo.ModeloFormal;
import br.uem.din.yandre.sctmf.model.pojo.Simbolo;
import br.uem.din.yandre.sctmf.model.services.ValidaSequencia;
import br.uem.din.yandre.sctmf.model.services.Validacao;
import br.uem.din.yandre.sctmf.view.modelos_formais.ModeloFormalGUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author  rafael2009_00
 */
public class ErGUI extends ModeloFormalGUI {

    private Validacao validacao = ValidaSequencia.getInstance();
    private br.uem.din.yandre.sctmf.view.components.GenericJList listAux = new br.uem.din.yandre.sctmf.view.components.GenericJList();

    /** Creates new form ErGUI */
    public ErGUI() {
        initComponents();
        posInitComponents();

    }

    public void setModeloFormal(ModeloFormal mf) {
        ER er = (ER) mf;
        this.listSimb.removeAllItens();
        this.fExprReg.setText("");

        for (Simbolo s : er.getAlfabeto()) {
            this.addAction(s);
        }

        this.fExprReg.setText(er.getExpressaoRegular());

    }

    public ModeloFormal getModeloFormal() {
        ER er = new ER();
        for (Object o : this.listSimb.getAllItens()) {
            er.addSimboAlf(new Simbolo((Character) o));
        }

        er.setExpressaoRegular(this.fExprReg.getText());

        return er;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        listSimb = new br.uem.din.yandre.sctmf.view.components.GenericJList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addRemButtons = new br.uem.din.yandre.sctmf.view.components.AddRemButtonsPanel();
        letterNumber = new br.uem.din.yandre.sctmf.view.components.LetterNumber();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fExprReg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        fSequencia = new javax.swing.JTextField();
        bTestar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setPreferredSize(new java.awt.Dimension(607, 75));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(listSimb, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("E");
        jLabel1.setText("\u03a3");
        jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);

        jLabel2.setPreferredSize(new java.awt.Dimension(0, 5));
        jPanel1.add(jLabel2, java.awt.BorderLayout.SOUTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 96;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel2.add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 50, 0, 0);
        jPanel2.add(addRemButtons, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 41, 0, 18);
        jPanel2.add(letterNumber, gridBagConstraints);

        add(jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(10, 5));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setPreferredSize(new java.awt.Dimension(30, 14));
        jPanel3.add(jLabel3, java.awt.BorderLayout.WEST);

        jLabel4.setPreferredSize(new java.awt.Dimension(30, 14));
        jPanel3.add(jLabel4, java.awt.BorderLayout.EAST);

        jPanel5.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel6.setText("Digite a expressão Regular:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel7.add(jLabel6, gridBagConstraints);

        jButton1.setText("?");
        jButton1.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(39, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(20, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        jPanel7.add(jButton1, gridBagConstraints);

        jLabel7.setText("    ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel7.add(jLabel7, gridBagConstraints);

        jLabel8.setText("     ");
        jPanel7.add(jLabel8, new java.awt.GridBagConstraints());

        jLabel9.setText("             ");
        jPanel7.add(jLabel9, new java.awt.GridBagConstraints());

        jLabel10.setText("                 ");
        jPanel7.add(jLabel10, new java.awt.GridBagConstraints());

        jPanel5.add(jPanel7);

        fExprReg.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        fExprReg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fExprReg.setAlignmentY(0.0F);
        fExprReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fExprRegActionPerformed(evt);
            }
        });
        fExprReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fExprRegKeyTyped(evt);
            }
        });
        jPanel5.add(fExprReg);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jLabel5.setPreferredSize(new java.awt.Dimension(34, 5));
        jPanel3.add(jLabel5, java.awt.BorderLayout.NORTH);

        add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Validação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        fSequencia.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        fSequencia.setPreferredSize(new java.awt.Dimension(150, 25));
        fSequencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fSequenciaKeyTyped(evt);
            }
        });
        jPanel4.add(fSequencia);

        bTestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/History24.gif"))); // NOI18N
        bTestar.setText("Testar");
        bTestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTestarActionPerformed(evt);
            }
        });
        jPanel4.add(bTestar);

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents

    private void bTestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTestarActionPerformed
        String valor = this.fExprReg.getText();
        int cont = 0;
        for (char c : valor.toCharArray()) {
            if (c == 40) {
                cont++;
            } else if (c == 41) {
                cont--;
            }
        }

        if (cont == 0) {
            validacao.valida(this.getModeloFormal(), this.fSequencia.getText());
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                    null, " Verifique os parenteses da ER!");
        }
    }//GEN-LAST:event_bTestarActionPerformed

    private void fSequenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fSequenciaKeyTyped

        if (!this.listSimb.containsItem(evt.getKeyChar())) {
            evt.setKeyChar(KeyEvent.CHAR_UNDEFINED);
        }
    }//GEN-LAST:event_fSequenciaKeyTyped

    private void fExprRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fExprRegActionPerformed
    }//GEN-LAST:event_fExprRegActionPerformed

    private void fExprRegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fExprRegKeyTyped
        if ((!this.listSimb.containsItem(evt.getKeyChar())) &&
                ((!this.listAux.containsItem(evt.getKeyChar())))) {
            evt.setKeyChar(KeyEvent.CHAR_UNDEFINED);
        }
    }//GEN-LAST:event_fExprRegKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "'(' e ')' \t Lista de caracteres. Casa " +
                "uma ocorrência de qualquer caractere contido na lista." +
                "Por exemplo, (abc) casa 'a', 'b' ou 'c'. \n"+
                "'*' \t Casa o elemento precedente zero ou mais vezes. " +
                "Por exemplo, ab*c casa \"ac\", \"abc\", \"abbbc\", etc.. \n"+
                "'+' \t Casa o elemento precedente uma ou mais vezes. Por exemplo, " +
                "ba+ casa \"ba\", \"baa\", \"baaa\", e assim por diante.",
                "Help", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void posInitComponents() {
        letterNumber.showCheck();

        this.addRemButtons.getBAdd().addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent ae) {
                addAction(null);
            }
        });

        this.addRemButtons.getBRemove().addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent ae) {
                removeAction();
            }
        });

        this.listAux.removeAllItens();
        this.listAux.addItem('(');
        this.listAux.addItem(')');
        this.listAux.addItem('+');
        this.listAux.addItem('*');
  

    }

    private void addAction(Simbolo s) {
        if (s == null) {
            s = new Simbolo(letterNumber.getValue());
        }

        final char name = s.getNome();
        if (this.listSimb.addItem(name) != null) {
        }

    }

    private void removeAction() {
        for (Object o : this.listSimb.removeItens()) {
            observerRemove((Character) o);
        }
    }

    private void observerRemove(Character c) {
        // Verifica se existe o simbolo na str, caso ache, remove
        String str = this.fExprReg.getText();
        str = str.replaceAll(c.toString(), "");
        this.fExprReg.setText(str);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.uem.din.yandre.sctmf.view.components.AddRemButtonsPanel addRemButtons;
    private javax.swing.JButton bTestar;
    private javax.swing.JTextField fExprReg;
    private javax.swing.JTextField fSequencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private br.uem.din.yandre.sctmf.view.components.LetterNumber letterNumber;
    private br.uem.din.yandre.sctmf.view.components.GenericJList listSimb;
    // End of variables declaration//GEN-END:variables
}
