/*
 * LetterNumber.java
 *
 * Created on 13 de Março de 2007, 08:38
 */

package br.uem.din.yandre.sctmf.view.components;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 *
 * @author  rafael2009_00
 */
public class LetterNumber extends javax.swing.JPanel {
    
    public static final int JCB_NUMBER = 1;
    public static final int JCB_LETTER = 2;
    
    /** Creates new form LetterNumber */
    public LetterNumber() {
        initComponents();
        buttonGroup.add(rbLetter);
        buttonGroup.add(rbNumber);
                
        jcb.setVisible(false);
    }
    
    public void setCustomTextInBorderTitle(String customText) {
        jPanel1.setBorder(
                javax.swing.BorderFactory.createTitledBorder(
                    new javax.swing.border.SoftBevelBorder(
                            javax.swing.border.BevelBorder.RAISED), 
                    customText, 
                    javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, 
                    javax.swing.border.TitledBorder.DEFAULT_POSITION, 
                    new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 51)));
    }
    
    public void hideRadioButtons() {
        rbLetter.setVisible(false);
        rbNumber.setVisible(false);
    }
    
    public void checkLetraMauscula() {
        jcb.setSelected(true);
    }
    
    public void showCheck() {
        jcb.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cbLetter = new javax.swing.JComboBox();
        cbNumber = new javax.swing.JComboBox();
        jcb = new javax.swing.JCheckBox();
        rbLetter = new javax.swing.JRadioButton();
        rbNumber = new javax.swing.JRadioButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Símbolos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(150, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(150, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 80));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        cbLetter.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18));
        cbLetter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" }));
        cbLetter.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(cbLetter, gridBagConstraints);

        cbNumber.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18));
        cbNumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cbNumber.setPreferredSize(new java.awt.Dimension(50, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(cbNumber, gridBagConstraints);

        jcb.setText("Letra Minúscula");
        jcb.setToolTipText("Letra Minúscula");
        jcb.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jcb.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jcb, gridBagConstraints);

        rbLetter.setSelected(true);
        rbLetter.setText("A-Z");
        rbLetter.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rbLetter.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(rbLetter, gridBagConstraints);

        rbNumber.setText("0-9");
        rbNumber.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rbNumber.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(rbNumber, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbActionPerformed
        
    public void enableCbNumber(boolean arg) {
        this.cbNumber.setEnabled(arg);
        this.rbNumber.setEnabled(arg);
    }
    
    public void enableCbLetter(boolean arg) {
        this.cbLetter.setEnabled(arg);
        this.rbLetter.setEnabled(arg);
    }
    
    public void enableRbNumber(boolean arg) {
        this.rbNumber.setEnabled(arg);
    }
    
    public void enableRbLetter(boolean arg) {
        this.rbLetter.setEnabled(arg);
    }
        
    private Character getLetter() {
        char c = this.cbLetter.getSelectedItem().toString().charAt(0);
        if(this.jcb.isSelected())
            return Character.toLowerCase(c);
        else
            return c;
    }
    
    private Character getNumber() {
        return this.cbNumber.getSelectedItem().toString().charAt(0);
    }
    
    public Character getValue() {
        if(rbLetter.isSelected())
            return this.getLetter();
        else 
            return this.getNumber();
    }
    
    public String getLetterAndNumber() {
        return ""+getLetter()+getNumber();
    }
    
    public void addItem(String s) {
        List<String> l = new ArrayList<String>();
        l.add(s); // add o simbolo
        int size = cbLetter.getModel().getSize();
        for(int i =0;i<size;i++) 
            l.add(cbLetter.getItemAt(i).toString());
        
        this.cbLetter.removeAllItems(); // remove todos os itens do JComoBox
        Collections.sort(l); // Ordena            
        for(String str : l)
            this.cbLetter.addItem(str);
        
    }
    
    public void removeItem(Object o) {
        this.cbLetter.removeItem(o.toString());        
    }
    
    /**
     * Forca as letras serem todas minúsculas
     */
    public void forceAllLowerCase(boolean status) {
        if(status) {
            this.jcb.setSelected(true);
            this.jcb.setEnabled(false);
            
        }else {        
            this.jcb.setSelected(false);
            this.jcb.setEnabled(true);
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox cbLetter;
    private javax.swing.JComboBox cbNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcb;
    private javax.swing.JRadioButton rbLetter;
    private javax.swing.JRadioButton rbNumber;
    // End of variables declaration//GEN-END:variables
    
}
