/*
 * ShowFitaMT.java
 *
 * Created on 13 de Novembro de 2007, 16:47
 */

package br.uem.din.yandre.sctmf.view.modelos_formais.ling_sens_cont.all.util;


import br.uem.din.yandre.sctmf.model.pojo.Simbolo;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author  rafael2009_00
 */
public class ShowFitaALL extends javax.swing.JDialog {
    
    private static final ShowFitaALL singleton = new ShowFitaALL();
    
    /** Creates new form ShowFitaMT */
    private ShowFitaALL() {
        setLocationRelativeTo(null);
        initComponents();
        setSize(600,120);
        setModal(true);
    }
    
    /**
     * Exibe a Fita do Automato Linearmente Limitado
     *
     * @param fitaMT
     */
     public void showFitaALL(List<Simbolo> fitaALL) {
         final int tamFita = fitaALL.size();
         pLabels.removeAll();
         //pLabels.setLayout(new java.awt.GridLayout(1, tamFita));
         pLabels.setLayout(new java.awt.GridLayout(1, 1));
         pLabels.add(createLabel('<'));
         for(Simbolo s : fitaALL)
            if(Character.isLetterOrDigit(s.getNome()))
                pLabels.add(createLabel(s.getNome()));           
         pLabels.add(createLabel('>'));
         setVisible(true);   
        
     }
     
     private JLabel createLabel(Character text) {
         final JLabel label = new JLabel(" "+text+" ");
         label.setFont(new java.awt.Font("Verdana", 0, 36));
         label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
         
         label.setBorder(
                javax.swing.BorderFactory
                    .createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                  
         return label;
     }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JScrollPane();
        pLabels = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fita do Automato Limitado Linearmente");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pane.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        pLabels.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        pane.setViewportView(pLabels);

        getContentPane().add(pane);

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pLabels;
    private javax.swing.JScrollPane pane;
    // End of variables declaration//GEN-END:variables
    
    public static final ShowFitaALL getInstance() {
        return singleton;
    }
    
}
