/*
 * ShowFitaMT.java
 *
 * Created on 13 de Novembro de 2007, 16:47
 */

package br.uem.din.yandre.sctmf.view.modelos_formais.ling_enum_rec.mt.util;

import br.uem.din.yandre.sctmf.model.pojo.Simbolo;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author  rafael2009_00
 */
public class ShowFitaMT extends javax.swing.JDialog {
    
    private static final ShowFitaMT singleton = new ShowFitaMT();
    
    /** Creates new form ShowFitaMT */
    private ShowFitaMT() {
        setLocationRelativeTo(null);
        initComponents();
        setSize(600,120);
        setModal(true);
    }
    
    /**
     * Exibe a Fita da Maquina de Turing
     *
     * @param fitaMT
     */
     public void showFitaMT(List<Simbolo> fitaMT) {   
         final int tamFita = fitaMT.size();
         pLabels.removeAll();
         //pLabels.setLayout(new java.awt.GridLayout(1, tamFita));
         pLabels.setLayout(new java.awt.GridLayout(1, 1));
         
         pLabels.add(createLabel('<'));
         for(Simbolo s : fitaMT)
            if(Character.isLetterOrDigit(s.getNome()))
                pLabels.add(createLabel(s.getNome()));           
         pLabels.add(createLabel('\u03B2'));
         pLabels.add(createLabel('\u03B2'));
         pLabels.add(createLabel('\u03B2'));
 
         setVisible(true);   
        
     }
     
     private JLabel createLabel(Character text) {
         final JLabel label = new JLabel(" "+text+" ");
         label.setFont(new java.awt.Font("Verdana", 0, 36));
         label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
         
         label.setBorder(
                javax.swing.BorderFactory
                    .createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                  
         return label;
     }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        pane = new javax.swing.JScrollPane();
        pLabels = new javax.swing.JPanel();

        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fita da M\u00e1quina de Turing");
        pane.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        pLabels.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        pane.setViewportView(pLabels);

        getContentPane().add(pane);

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JPanel pLabels;
    private javax.swing.JScrollPane pane;
    // Fim da declaração de variáveis//GEN-END:variables
    
    public static final ShowFitaMT getInstance() {
        return singleton;
    }
    
}
