/*
 * CadEst.java
 *
 * Created on 3 de Maio de 2007, 10:22
 */

package cassolato.rafael.sctmf.view.formalmodels.afd;

import cassolato.rafael.sctmf.model.pojo.Estado;
import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 *
 * @author  rafael2009_00
 */
class CadEst extends javax.swing.JPanel {
    
    /** Creates new form CadEst */
    public CadEst() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        bAddEst = new javax.swing.JButton();
        bRemEst = new javax.swing.JButton();
        bAddEstIni = new javax.swing.JButton();
        bRemEstIni = new javax.swing.JButton();
        bAddEstFin = new javax.swing.JButton();
        bRemEstFin = new javax.swing.JButton();
        pNorte = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        letterNumber = new view.LetterNumber();
        jPanel26 = new javax.swing.JPanel();
        addRemEst = new view.AddRemButtonsPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        listEstados = new cassolato.rafael.sctmf.view.components.GenericJList();
        pSul = new javax.swing.JPanel();
        pEstIni = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        cbEstIni = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        addRemEstIni = new view.AddRemButtonsPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        listEstIni = new cassolato.rafael.sctmf.view.components.GenericJList();
        pEstFin = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        cbEstFin = new javax.swing.JComboBox();
        jPanel41 = new javax.swing.JPanel();
        addRemEstFin = new view.AddRemButtonsPanel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        listEstFin = new cassolato.rafael.sctmf.view.components.GenericJList();

        bAddEst.setText("jButton1");
        bAddEst = addRemEst.getButton(addRemEst.ADD);
        bAddEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddEstActionPerformed(evt);
            }
        });

        bRemEst.setText("jButton2");
        bRemEst = addRemEst.getButton(addRemEst.REMOVE);
        bRemEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemEstActionPerformed(evt);
            }
        });

        bAddEstIni.setText("jButton3");
        bAddEstIni = addRemEstIni.getButton(addRemEstIni.ADD);
        bAddEstIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddEstIniActionPerformed(evt);
            }
        });

        bRemEstIni.setText("jButton4");
        bRemEstIni = addRemEstIni.getButton(addRemEstIni.REMOVE);
        bRemEstIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemEstIniActionPerformed(evt);
            }
        });

        bAddEstFin.setText("jButton5");
        bAddEstFin = addRemEstFin.getButton(addRemEstFin.ADD);
        bAddEstFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddEstFinActionPerformed(evt);
            }
        });

        bRemEstFin.setText("jButton6");
        bRemEstFin = addRemEstFin.getButton(addRemEstFin.REMOVE);
        bRemEstFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemEstFinActionPerformed(evt);
            }
        });

        setLayout(new java.awt.GridLayout(2, 0));

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Cadastramento de Estados ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255)));
        pNorte.setLayout(new javax.swing.BoxLayout(pNorte, javax.swing.BoxLayout.X_AXIS));

        jPanel25.add(letterNumber);

        pNorte.add(jPanel25);

        jPanel26.setLayout(new java.awt.BorderLayout());

        jPanel26.setMaximumSize(new java.awt.Dimension(80, 180));
        jPanel26.setMinimumSize(new java.awt.Dimension(80, 180));
        jPanel26.setPreferredSize(new java.awt.Dimension(80, 180));
        addRemEst.setPreferredSize(new java.awt.Dimension(70, 140));
        jPanel26.add(addRemEst, java.awt.BorderLayout.CENTER);

        jLabel42.setPreferredSize(new java.awt.Dimension(34, 20));
        jPanel26.add(jLabel42, java.awt.BorderLayout.NORTH);

        jLabel43.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel26.add(jLabel43, java.awt.BorderLayout.SOUTH);

        jLabel44.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel26.add(jLabel44, java.awt.BorderLayout.WEST);

        pNorte.add(jPanel26);

        jPanel27.setLayout(new java.awt.BorderLayout());

        jPanel27.setMinimumSize(new java.awt.Dimension(50, 42));
        jLabel46.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Estados");
        jPanel27.add(jLabel46, java.awt.BorderLayout.NORTH);

        jLabel47.setPreferredSize(new java.awt.Dimension(40, 0));
        jPanel27.add(jLabel47, java.awt.BorderLayout.WEST);

        jLabel48.setPreferredSize(new java.awt.Dimension(40, 0));
        jPanel27.add(jLabel48, java.awt.BorderLayout.EAST);

        jPanel27.add(listEstados, java.awt.BorderLayout.CENTER);

        pNorte.add(jPanel27);

        add(pNorte);

        pSul.setLayout(new java.awt.GridLayout(1, 2));

        pSul.setPreferredSize(new java.awt.Dimension(10, 150));
        pEstIni.setLayout(new java.awt.BorderLayout());

        pEstIni.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Estado Inicial ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(19, 92, 34)));
        jLabel77.setPreferredSize(new java.awt.Dimension(0, 5));
        pEstIni.add(jLabel77, java.awt.BorderLayout.SOUTH);

        jLabel78.setPreferredSize(new java.awt.Dimension(5, 0));
        pEstIni.add(jLabel78, java.awt.BorderLayout.WEST);

        jPanel5.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 25));

        cbEstIni.setFont(new java.awt.Font("Tahoma", 1, 14));
        cbEstIni.setPreferredSize(new java.awt.Dimension(50, 22));
        jPanel6.add(cbEstIni);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        addRemEstIni.setPreferredSize(new java.awt.Dimension(59, 140));
        jPanel7.add(addRemEstIni, java.awt.BorderLayout.CENTER);

        jLabel79.setPreferredSize(new java.awt.Dimension(0, 5));
        jPanel7.add(jLabel79, java.awt.BorderLayout.NORTH);

        jLabel80.setPreferredSize(new java.awt.Dimension(0, 5));
        jPanel7.add(jLabel80, java.awt.BorderLayout.SOUTH);

        jPanel5.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel8.add(listEstIni, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8);

        pEstIni.add(jPanel5, java.awt.BorderLayout.CENTER);

        pSul.add(pEstIni);

        pEstFin.setLayout(new java.awt.BorderLayout());

        pEstFin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estados Finais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(125, 82, 134)));
        jLabel81.setPreferredSize(new java.awt.Dimension(0, 5));
        pEstFin.add(jLabel81, java.awt.BorderLayout.SOUTH);

        jLabel82.setPreferredSize(new java.awt.Dimension(10, 0));
        pEstFin.add(jLabel82, java.awt.BorderLayout.WEST);

        panel.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        jPanel40.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 25));

        cbEstFin.setFont(new java.awt.Font("Tahoma", 1, 14));
        cbEstFin.setPreferredSize(new java.awt.Dimension(50, 22));
        jPanel40.add(cbEstFin);

        panel.add(jPanel40);

        jPanel41.setLayout(new java.awt.BorderLayout());

        addRemEstFin.setPreferredSize(new java.awt.Dimension(59, 140));
        jPanel41.add(addRemEstFin, java.awt.BorderLayout.CENTER);

        jLabel83.setPreferredSize(new java.awt.Dimension(0, 5));
        jPanel41.add(jLabel83, java.awt.BorderLayout.NORTH);

        jLabel84.setPreferredSize(new java.awt.Dimension(0, 5));
        jPanel41.add(jLabel84, java.awt.BorderLayout.SOUTH);

        panel.add(jPanel41);

        jPanel42.setLayout(new java.awt.BorderLayout());

        jPanel42.add(listEstFin, java.awt.BorderLayout.CENTER);

        panel.add(jPanel42);

        pEstFin.add(panel, java.awt.BorderLayout.CENTER);

        pSul.add(pEstFin);

        add(pSul);

    }// </editor-fold>//GEN-END:initComponents

    private void bRemEstFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemEstFinActionPerformed
        this.listEstFin.removeItens();
    }//GEN-LAST:event_bRemEstFinActionPerformed

    private void bAddEstFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddEstFinActionPerformed
        Object item = this.cbEstFin.getSelectedItem();
        if(item!=null) 
            this.listEstFin.addItem(item.toString());
        
    }//GEN-LAST:event_bAddEstFinActionPerformed

    private void bRemEstIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemEstIniActionPerformed
        this.listEstIni.removeItens();
    }//GEN-LAST:event_bRemEstIniActionPerformed

    private void bAddEstIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddEstIniActionPerformed
        Object item = this.cbEstIni.getSelectedItem();
        if(item!=null) {
            this.listEstIni.removeAllItens();
            this.listEstIni.addItem(item.toString());
        }            
    }//GEN-LAST:event_bAddEstIniActionPerformed

    private void bRemEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemEstActionPerformed
       for(Object o : listEstados.removeItens())
            this.observerRemove(o);
    }//GEN-LAST:event_bRemEstActionPerformed

    private void bAddEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddEstActionPerformed
        String estado = letterNumber.getLetter()+""+letterNumber.getNumber();
        
        if(this.listEstados.addItem(estado))  
            this.observerAdd(estado);
    }//GEN-LAST:event_bAddEstActionPerformed
    
    /**
     * Método observer para as operacoes de 
     * ADD no painel de cadastro de estados.
     *
     * @param item
     */
    private void observerAdd(String item) {   
        cbEstIni.addItem(item);
        cbEstFin.addItem(item);        
    }
    
    /**
     * Método observer para as operacoes de 
     * REMOVE no painel de cadastro de estados.
     *
     * @param item
     */
    private void observerRemove(Object item) {
        // Estado Inicial
        this.cbEstIni.removeItem(item);
        this.listEstIni.removeItem(item);
        
        // Estados Finais
        this.cbEstFin.removeItem(item);
        this.listEstFin.removeItem(item);
    }
    
    void setEstados(Collection<Estado> estados) {
        this.listEstados.removeAllItens();
        
        Iterator<Estado> i = estados.iterator();
        while(i.hasNext())
            this.listEstados.addItem(i.next().getNome());
    }
    
    Collection<Estado> getEstados() {
        Set<Estado> estados = new LinkedHashSet<Estado>();
        Iterator<Object> i = this.listEstados.getAllItens().iterator();
        while(i.hasNext())
            estados.add(new Estado(i.next().toString()));
        
        return estados;        
    }
    
    void setEstadoInicial(Estado ei) {
        
    }
    
    Estado getEstadoInicial() {
        for(Object o :listEstIni.getAllItens())
            return new Estado(o.toString());
        
        return null;
    }
    
    void setEstadosFinais(Collection<Estado> ef) {
        
    }
    
    Collection<Estado> getEstadosFinais() {
        Set<Estado> estFin = new LinkedHashSet<Estado>();
        Iterator<Object> i = this.listEstFin.getAllItens().iterator();
        while(i.hasNext())
            estFin.add(new Estado(i.next().toString()));
        
        return estFin;  
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.AddRemButtonsPanel addRemEst;
    private view.AddRemButtonsPanel addRemEstFin;
    private view.AddRemButtonsPanel addRemEstIni;
    private javax.swing.JButton bAddEst;
    private javax.swing.JButton bAddEstFin;
    private javax.swing.JButton bAddEstIni;
    private javax.swing.JButton bRemEst;
    private javax.swing.JButton bRemEstFin;
    private javax.swing.JButton bRemEstIni;
    private javax.swing.JComboBox cbEstFin;
    private javax.swing.JComboBox cbEstIni;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private view.LetterNumber letterNumber;
    private cassolato.rafael.sctmf.view.components.GenericJList listEstFin;
    private cassolato.rafael.sctmf.view.components.GenericJList listEstIni;
    private cassolato.rafael.sctmf.view.components.GenericJList listEstados;
    private javax.swing.JPanel pEstFin;
    private javax.swing.JPanel pEstIni;
    private javax.swing.JPanel pNorte;
    private javax.swing.JPanel pSul;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
    
}
