/*
 * CadEstMT.java
 *
 * Created on 23 de Agosto de 2007, 08:52
 */

package br.uem.din.yandre.sctmf.view.modelos_formais.ling_sens_cont.all;

import br.uem.din.yandre.sctmf.model.pojo.Estado;
import br.uem.din.yandre.sctmf.view.components.CEstado;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 *
 * @author  rafael2009_00
 */
public class CadEstALL extends javax.swing.JPanel implements CEstado {
    private AllGUI gui = null;
    
    /** Creates new form CadEstMT */
    public CadEstALL(AllGUI gui) {
        this.gui = gui;
        
        initComponents();
        posInitComponents();
    }
    
    Set<Estado> getEstados() {
        return this.cadEstado.getAllItens();        
    }
    
    Estado getEstadoInicial() {
        Collection<Object> o = this.listEstIni.getAllItens();
        return o.size()>0?new Estado(o.iterator().next().toString()):null;
    }
    
    Set<Estado> getEstadosFinais() {        
        LinkedHashSet<Estado> estados = new LinkedHashSet<Estado>();
        for(Object o : this.listEstFin.getAllItens()) 
            estados.add(new Estado(o.toString()));
        
        return estados;
    }
    
    void setEstados(Set<Estado> estados) {
        this.cadEstado.removeAllItens();
        
        for(Estado e : estados)
            this.cadEstado.addEstado(e);               
    }
    
    void setEstadoInicial(Estado estado) {
       this.listEstIni.removeAllItens();   
       this.listEstIni.addItem(estado.getNome());
    }
    
    void setEstadosFinais(Set<Estado> estFin) {
       this.listEstFin.removeAllItens();
       
       for(Estado e : estFin)
           this.listEstFin.addItem(e.getNome()); 
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadEstado = cadEstado = new br.uem.din.yandre.sctmf.view.components.CadEstado(this);
        pSul = new javax.swing.JPanel();
        pEstIni = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        cbEstIni = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        addRemEstIni = new br.uem.din.yandre.sctmf.view.components.AddRemButtonsPanel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        listEstIni = new br.uem.din.yandre.sctmf.view.components.GenericJList();
        pEstFin = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        cbEstFin = new javax.swing.JComboBox();
        jPanel41 = new javax.swing.JPanel();
        addRemEstFin = new br.uem.din.yandre.sctmf.view.components.AddRemButtonsPanel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        listEstFin = new br.uem.din.yandre.sctmf.view.components.GenericJList();

        setLayout(new java.awt.GridLayout(2, 0));
        add(cadEstado);

        pSul.setPreferredSize(new java.awt.Dimension(10, 150));
        pSul.setLayout(new java.awt.GridLayout(1, 2));

        pEstIni.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Estado Inicial ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(19, 92, 34))); // NOI18N
        pEstIni.setLayout(new java.awt.BorderLayout());

        jLabel77.setPreferredSize(new java.awt.Dimension(0, 5));
        pEstIni.add(jLabel77, java.awt.BorderLayout.SOUTH);

        jLabel78.setPreferredSize(new java.awt.Dimension(5, 0));
        pEstIni.add(jLabel78, java.awt.BorderLayout.WEST);

        jPanel5.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 25));

        cbEstIni.setFont(new java.awt.Font("Tahoma", 1, 14));
        cbEstIni.setPreferredSize(new java.awt.Dimension(50, 22));
        jPanel6.add(cbEstIni);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        addRemEstIni.setPreferredSize(new java.awt.Dimension(59, 140));
        jPanel7.add(addRemEstIni, java.awt.BorderLayout.CENTER);

        jLabel79.setPreferredSize(new java.awt.Dimension(0, 5));
        jPanel7.add(jLabel79, java.awt.BorderLayout.NORTH);

        jLabel80.setPreferredSize(new java.awt.Dimension(0, 5));
        jPanel7.add(jLabel80, java.awt.BorderLayout.SOUTH);

        jPanel5.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel8.add(listEstIni, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8);

        pEstIni.add(jPanel5, java.awt.BorderLayout.CENTER);

        pSul.add(pEstIni);

        pEstFin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estados Finais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(125, 82, 134))); // NOI18N
        pEstFin.setLayout(new java.awt.BorderLayout());

        jLabel81.setPreferredSize(new java.awt.Dimension(0, 5));
        pEstFin.add(jLabel81, java.awt.BorderLayout.SOUTH);

        jLabel82.setPreferredSize(new java.awt.Dimension(10, 0));
        pEstFin.add(jLabel82, java.awt.BorderLayout.WEST);

        panel.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        jPanel40.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 25));

        cbEstFin.setFont(new java.awt.Font("Tahoma", 1, 14));
        cbEstFin.setPreferredSize(new java.awt.Dimension(50, 22));
        jPanel40.add(cbEstFin);

        panel.add(jPanel40);

        jPanel41.setLayout(new java.awt.BorderLayout());

        addRemEstFin.setPreferredSize(new java.awt.Dimension(59, 140));
        jPanel41.add(addRemEstFin, java.awt.BorderLayout.CENTER);

        jLabel83.setPreferredSize(new java.awt.Dimension(0, 5));
        jPanel41.add(jLabel83, java.awt.BorderLayout.NORTH);

        jLabel84.setPreferredSize(new java.awt.Dimension(0, 5));
        jPanel41.add(jLabel84, java.awt.BorderLayout.SOUTH);

        panel.add(jPanel41);

        jPanel42.setLayout(new java.awt.BorderLayout());
        jPanel42.add(listEstFin, java.awt.BorderLayout.CENTER);

        panel.add(jPanel42);

        pEstFin.add(panel, java.awt.BorderLayout.CENTER);

        pSul.add(pEstFin);

        add(pSul);
    }// </editor-fold>//GEN-END:initComponents

    private void posInitComponents() {         
        this.addRemEstIni.getBAdd().addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae) {
                addActionEstadoInicial();
            }
        });
        
        this.addRemEstIni.getBRemove().addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae) {
                removeActionEstadoInicial();
            }
        });
        
        this.addRemEstFin.getBAdd().addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae) {
                addActionEstadoFinal();
            }
        });
        
        this.addRemEstFin.getBRemove().addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae) {
                removeActionEstadoFinal();
            }
        });
    }
    
    private void removeActionEstadoInicial() {
         this.listEstIni.removeItens(); 
    }
    
    private void addActionEstadoInicial() {
        Object item = this.cbEstIni.getSelectedItem();
        if(item!=null) {
            this.listEstIni.removeAllItens();
            this.listEstIni.addItem(item.toString());
        } 
    }
    
    private void removeActionEstadoFinal() {
        this.listEstFin.removeItens();
    }
    
    private void addActionEstadoFinal() {
        Object item = this.cbEstFin.getSelectedItem();
        if(item!=null) 
            this.listEstFin.addItem(item.toString());
    }
    
    public void addEstado(Estado estado) {
        this.gui.addEstado(estado);
        
        final String nomeEstado = estado.getNome();
        
        this.cbEstIni.addItem(nomeEstado);        
        this.cbEstFin.addItem(nomeEstado);     
    }

    public void remEstados(Set<Estado> estados) {
        for(Estado e : estados) {
            this.gui.removeEstado(e);
            
            String nomeEstado = e.getNome();
            
            this.cbEstIni.removeItem(nomeEstado);
            this.listEstIni.removeItem(nomeEstado);
            
            this.cbEstFin.removeItem(nomeEstado);
            this.listEstFin.removeItem(nomeEstado);
        }
    }

    public void removeAllItens() {        
        this.cbEstIni.removeAllItems();
        this.listEstIni.removeAllItens();
        
        this.cbEstFin.removeAllItems();
        this.listEstFin.removeAllItens();
    }          
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.uem.din.yandre.sctmf.view.components.AddRemButtonsPanel addRemEstFin;
    private br.uem.din.yandre.sctmf.view.components.AddRemButtonsPanel addRemEstIni;
    private br.uem.din.yandre.sctmf.view.components.CadEstado cadEstado;
    private javax.swing.JComboBox cbEstFin;
    private javax.swing.JComboBox cbEstIni;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private br.uem.din.yandre.sctmf.view.components.GenericJList listEstFin;
    private br.uem.din.yandre.sctmf.view.components.GenericJList listEstIni;
    private javax.swing.JPanel pEstFin;
    private javax.swing.JPanel pEstIni;
    private javax.swing.JPanel pSul;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
  
}