package br.uem.din.yandre.sctmf.view.modelos_formais.ling_enum_rec.post;

import br.uem.din.yandre.sctmf.model.pojo.MT;
import br.uem.din.yandre.sctmf.model.pojo.ModeloFormal;
import br.uem.din.yandre.sctmf.model.pojo.Post;
import br.uem.din.yandre.sctmf.view.modelos_formais.ModeloFormalGUI;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.netbeans.api.visual.widget.Widget;

/**
 *
 * @author  michelmenega
 */
public class PostGUI extends ModeloFormalGUI implements CustomGraphSceneSelectionListener {

    private CadAlfPost cadAlf = new CadAlfPost(this);
    private DiagramaPost diagrama = new DiagramaPost(this);
    CustomGraphScene scene;
    JScrollPane scrollPane = new JScrollPane();

    /** Creates new form PostGUI */
    public PostGUI() {

        initComponents();
        
        initScene();
        scene.addSelectionListener(this);
        bSelecao.setSelected(true);
        //Set the layout:
        //pDiagrama.setLayout(new BorderLayout());
        //Create a JScrollPane:

        //Add the JScrollPane to the JPanel:
        //pDiagrama.add(scrollPane, BorderLayout.CENTER);
        //Create the GraphSceneImpl:
        //GraphScene scene = new GraphSceneImpl();
        //Add it to the JScrollPane:
        //scrollPane.setViewportView(scene.createView());
        //Add the SatellitView to the scene:
        //pDiagrama.add(scene.createSatelliteView(), BorderLayout.WEST);


    }

    private void initScene() {
        CustomGraphScene s = new CustomGraphScene();
        scene = s;
//        Widget oi = s.addNode("oi");
//        oi.setPreferredLocation(new Point(100, 100));

        scrollPane.setViewportView(scene.createView());
        s.setSceneTool(SceneTool.SELECAO);
        pDiagrama.add(scrollPane, BorderLayout.CENTER);

    }

    public void update(CustomGraphScene s, Widget selected, Widget previous) {
        if (s == scene) {
            if (selected instanceof MostravelNaTela) {
                JPanel panel = ((MostravelNaTela) selected).getPanel();
                scrollPane.setViewportView(panel);
                ((MostravelNaTela) selected).loadState();
            }
            if (previous != null && previous instanceof MostravelNaTela) {
                ((MostravelNaTela) (previous)).saveState();
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tpMT = new javax.swing.JTabbedPane();
        pCadAlf = new javax.swing.JPanel();
        pDiagrama = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        bEstadoPartida = new javax.swing.JToggleButton();
        bEstadoParada = new javax.swing.JToggleButton();
        bEstadoLer = new javax.swing.JToggleButton();
        bEstadoAtribuicao = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        bConexao = new javax.swing.JToggleButton();
        bSelecao = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        bFix = new javax.swing.JButton();
        pValSeq = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pCadAlf.add(this.cadAlf);
        pCadAlf.setLayout(new java.awt.GridLayout(1, 0));
        tpMT.addTab("Alfabetos", pCadAlf);

        pDiagrama.add(this.diagrama);
        pDiagrama.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        buttonGroup1.add(bEstadoPartida);
        bEstadoPartida.setText("Partida");
        bEstadoPartida.setFocusable(false);
        bEstadoPartida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEstadoPartida.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bEstadoPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEstadoPartidaActionPerformed(evt);
            }
        });
        jToolBar1.add(bEstadoPartida);

        buttonGroup1.add(bEstadoParada);
        bEstadoParada.setText("Parada");
        bEstadoParada.setFocusable(false);
        bEstadoParada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEstadoParada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bEstadoParada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEstadoParadaActionPerformed(evt);
            }
        });
        jToolBar1.add(bEstadoParada);

        buttonGroup1.add(bEstadoLer);
        bEstadoLer.setText("Ler");
        bEstadoLer.setFocusable(false);
        bEstadoLer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEstadoLer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bEstadoLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEstadoLerActionPerformed(evt);
            }
        });
        jToolBar1.add(bEstadoLer);

        buttonGroup1.add(bEstadoAtribuicao);
        bEstadoAtribuicao.setText("Atribuicao");
        bEstadoAtribuicao.setFocusable(false);
        bEstadoAtribuicao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEstadoAtribuicao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bEstadoAtribuicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEstadoAtribuicaoActionPerformed(evt);
            }
        });
        jToolBar1.add(bEstadoAtribuicao);
        jToolBar1.add(jSeparator1);

        buttonGroup1.add(bConexao);
        bConexao.setText("Conexao");
        bConexao.setFocusable(false);
        bConexao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bConexao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConexaoActionPerformed(evt);
            }
        });
        jToolBar1.add(bConexao);

        buttonGroup1.add(bSelecao);
        bSelecao.setText("Selecao");
        bSelecao.setFocusable(false);
        bSelecao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSelecao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bSelecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelecaoActionPerformed(evt);
            }
        });
        jToolBar1.add(bSelecao);
        jToolBar1.add(jSeparator2);

        bFix.setText("Fix");
        bFix.setFocusable(false);
        bFix.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bFix.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bFix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFixActionPerformed(evt);
            }
        });
        jToolBar1.add(bFix);

        pDiagrama.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        tpMT.addTab("Diagrama", pDiagrama);

        pValSeq.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pValSeqComponentShown(evt);
            }
        });
        pValSeq.setLayout(new java.awt.GridLayout(1, 0));
        tpMT.addTab("Valid. Sequência", pValSeq);

        add(tpMT, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void pValSeqComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pValSeqComponentShown
        //this.valSeq.observer((Post)this.getModeloFormal());
}//GEN-LAST:event_pValSeqComponentShown

    private void bEstadoPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEstadoPartidaActionPerformed
        if (bEstadoPartida.isSelected()) {
            scene.setSceneTool(SceneTool.INSERCAO);
        }
    }//GEN-LAST:event_bEstadoPartidaActionPerformed

    private void bConexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConexaoActionPerformed
        if (bConexao.isSelected()) {
            scene.setSceneTool(SceneTool.ASSOCIACAO);
        }
    }//GEN-LAST:event_bConexaoActionPerformed

    private void bSelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelecaoActionPerformed
        if (bSelecao.isSelected()) {
            scene.setSceneTool(SceneTool.SELECAO);
        }
    }//GEN-LAST:event_bSelecaoActionPerformed

    private void bEstadoParadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEstadoParadaActionPerformed
        if (bEstadoParada.isSelected()) {
            scene.setSceneTool(SceneTool.INSERCAO);
        }
    }//GEN-LAST:event_bEstadoParadaActionPerformed

    private void bEstadoLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEstadoLerActionPerformed
        if (bEstadoLer.isSelected()) {
            scene.setSceneTool(SceneTool.INSERCAO);
        }
    }//GEN-LAST:event_bEstadoLerActionPerformed

    private void bEstadoAtribuicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEstadoAtribuicaoActionPerformed
        if (bEstadoAtribuicao.isSelected()) {
            scene.setSceneTool(SceneTool.INSERCAO);
        }
    }//GEN-LAST:event_bEstadoAtribuicaoActionPerformed

    private void bFixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFixActionPerformed
        scene.doGridLayout();
    }//GEN-LAST:event_bFixActionPerformed

    public void setModeloFormal(ModeloFormal mf) {
        Post post = (Post) mf;
        /*        this.cadAlf.setSimbAfabeto(mt.getAlfabeto());
        this.cadAlf.setSimbAfabetoAux(mt.getAlfabetoAux());
        
        /*       this.cadEst.setEstados(mt.getEstados());
        this.cadEst.setEstadoInicial(mt.getEstIni());
        this.cadEst.setEstadosFinais(mt.getEstFinais());
        
        this.cadFTrans.setTransicoes(mt.getTransicoes());*/

        this.tpMT.setSelectedIndex(0);
    }

    public ModeloFormal getModeloFormal() {
        MT mt = new MT();
        mt.setAlfabeto(this.cadAlf.getSimbAfabeto());
        mt.setAlfabetoAux(this.cadAlf.getSimbAfabetoAux());

        /*   mt.setEstados(this.cadEst.getEstados());
        mt.setEstIni(this.cadEst.getEstadoInicial());
        mt.setEstFinais(this.cadEst.getEstadosFinais());
        
        mt.setTransicoes(this.cadFTrans.getTransicoes()); */

        return mt;
    }

    /*
    void addSimbolo(Simbolo simbolo, int cod) {
    this.cadFTrans.observer(simbolo, true, cod);
    }
    
    void removeSimbolo(Simbolo simbolo, int cod) {
    this.cadFTrans.observer(simbolo, false, cod);
    }

    void addEstado(Estado estado) {
    this.cadFTrans.observer(estado, true);
    }
    
    void removeEstado(Estado estado) {
    this.cadFTrans.observer(estado, false);
    }    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JToggleButton bConexao;
    public static javax.swing.JToggleButton bEstadoAtribuicao;
    public static javax.swing.JToggleButton bEstadoLer;
    public static javax.swing.JToggleButton bEstadoParada;
    public static javax.swing.JToggleButton bEstadoPartida;
    private javax.swing.JButton bFix;
    public static javax.swing.JToggleButton bSelecao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pCadAlf;
    private javax.swing.JPanel pDiagrama;
    private javax.swing.JPanel pValSeq;
    private javax.swing.JTabbedPane tpMT;
    // End of variables declaration//GEN-END:variables
    }
