/*
 * ValSeqMT.java
 *
 * Created on 23 de Agosto de 2007, 09:06
 */
package br.uem.din.yandre.sctmf.view.modelos_formais.ling_enum_rec.post;

import br.uem.din.yandre.sctmf.model.pojo.Estado;
import br.uem.din.yandre.sctmf.model.pojo.Post;
import br.uem.din.yandre.sctmf.model.pojo.Simbolo;
import br.uem.din.yandre.sctmf.model.pojo.TransicaoPost;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author  michelmenega
 */
public class ValSeqPost extends javax.swing.JPanel {

    private PostGUI gui = null;

    /** Creates new form ValSeqMT */
    public ValSeqPost(PostGUI gui) {
        this.gui = gui;
        initComponents();
        posInitComponents();
    }

    void observer(Post post) {
        this.validaSequenciaGUI.clearArea();
        this.validaSequenciaGUI.setTextAInf(
                "M = \u03a3, D, #\n");

        StringBuffer sb = new StringBuffer();
        sb.append("\u03a3 = {");  // Add Simbolos
        for (Simbolo s : post.getAlfabeto()) {
            sb.append(s.getNome() + ", ");
        }
        sb = this.validaSequenciaGUI.formataSb(sb);

        sb.append("D = {"); // Add Estados
        for (Estado e : post.getEstados()) {
            sb.append(e.getNome() + "\n, ");
        }
        sb = this.validaSequenciaGUI.formataSb(sb);

        for (TransicaoPost t : post.getTransicoes()) {
            sb.append("\n").
                    append("\u03B4(").
                    append(t.getEstadoOrigem().getNome()).
                    append(") -> \n(").
                    append(t.getEstadoDestino().getNome()).
                    append(")");
        }
        this.validaSequenciaGUI.setTextAInf(sb.toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        validaSequenciaGUI = new br.uem.din.yandre.sctmf.view.components.ValidaSequenciaGUI();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());
        add(validaSequenciaGUI, java.awt.BorderLayout.CENTER);

        jLabel1.setPreferredSize(new java.awt.Dimension(0, 10));
        add(jLabel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void posInitComponents() {
        this.validaSequenciaGUI.setSplitPaneLocation(150);

        this.validaSequenciaGUI.getBValidar().addActionListener(
                new ActionListener() {

                    public void actionPerformed(ActionEvent ae) {
                        validarSequencia();
                    }
                });

    }

    private void validarSequencia() {
        this.validaSequenciaGUI.validarSequencia(
                (Post) this.gui.getModeloFormal(),
                this.validaSequenciaGUI.getSequencia());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private br.uem.din.yandre.sctmf.view.components.ValidaSequenciaGUI validaSequenciaGUI;
    // End of variables declaration//GEN-END:variables
}
