/*
 * CadFunTransGLC.java
 *
 * Created on 7 de Agosto de 2007, 09:13
 */

package br.uem.din.yandre.sctmf.view.modelos_formais.ling_liv_contex.glc;

import br.uem.din.yandre.sctmf.model.pojo.GLC;
import br.uem.din.yandre.sctmf.model.pojo.RegraProducao;
import br.uem.din.yandre.sctmf.model.pojo.SimboloString;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;

/**
 *
 * @author  rafael2009_00
 */
public class CadFunTransGLC extends javax.swing.JPanel {
    private Set<SimboloString> simbTerm = new LinkedHashSet<SimboloString>();
    private Set<SimboloString> simbNTerm = new LinkedHashSet<SimboloString>();
    private Vector<JPanel> rpsPanel = new Vector();
    
    /**
     * Creates new form CadFunTransGLC
     */
    public CadFunTransGLC() {
        initComponents();
        posInitComponents();
    }
    
    /**
     * Metodo observer para inclusao e exclusao de simbolos
     */
    void observer(Set<SimboloString> simbTerm, Set<SimboloString> simbNTerm) {
       this.simbTerm = simbTerm;
       this.simbNTerm = simbNTerm;
       
       // guarda o antigo simbolo inicial
       Object o = cbSimbIni.getSelectedItem(); 
       
       formaSentencial.removeTodosSimbolos();
       for (SimboloString s : simbTerm) formaSentencial.adicionaSimbolo(s);
       
       cbEsq.removeAllItems();
       cbSimbIni.removeAllItems();
       for(SimboloString s : simbNTerm) {
           cbEsq.addItem(s.getNome());
           cbSimbIni.addItem(s.getNome());
           formaSentencial.adicionaSimbolo(s);
       }
       
       // Seleciona novamente o simbolo inicial
       if(o!=null) {
           String item = (String)o;
           for(SimboloString s : simbNTerm)
               if(s.getNome().equals(item))
                   cbSimbIni.setSelectedItem(item);
       }
    }
    
    Set<RegraProducao> getProducoes() {
        Set<RegraProducao> producoes = new LinkedHashSet<RegraProducao>();
        for(JPanel jp : this.rpsPanel) {
            Component rpComp[] = jp.getComponents();
            RegraProducao rp = new RegraProducao();
            rp.setSimbLEsq(new SimboloString(((JLabel)rpComp[0]).getText()));

            List<SimboloString> sLDireito = new ArrayList<SimboloString>();
            for(int i = 2; i < rpComp.length; i++)
                sLDireito.add(new SimboloString(((JLabel)rpComp[i]).getText()));

            rp.setSimbLDireito(sLDireito);

            producoes.add(rp);
        }
        
        return producoes;
    }
    
    void setProducoes(Set<RegraProducao> regrasProducao) {
        listRProd.removeAll();
        for(RegraProducao rp : regrasProducao)
            this.addAction(rp.getSimbLEsq(), rp.getSimbLDireito());
    }
    
    SimboloString getSimboloInicial() {
        Object o = cbSimbIni.getSelectedItem();        
        return (o!=null)?new SimboloString(o.toString()):null;
    }
    
     void setSimbInicial(SimboloString simbolo) {
        this.cbSimbIni.setSelectedItem(simbolo.getNome());
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        addRemButtonsPanel = new br.uem.din.yandre.sctmf.view.components.AddRemButtonsPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cbEsq = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        fExpres = new javax.swing.JPanel();
        formaSentencial = new br.uem.din.yandre.sctmf.view.modelos_formais.ling_liv_contex.glc.FormaSentencial();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbSimbIni = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRProd = new javax.swing.JList();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMinimumSize(new java.awt.Dimension(280, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(280, 10));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel4.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel3.add(jLabel4, java.awt.BorderLayout.NORTH);

        jLabel5.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel3.add(jLabel5, java.awt.BorderLayout.SOUTH);

        jPanel7.setLayout(new java.awt.BorderLayout());

        addRemButtonsPanel.setMaximumSize(new java.awt.Dimension(32767, 38));
        addRemButtonsPanel.setMinimumSize(new java.awt.Dimension(57, 38));
        addRemButtonsPanel.setPreferredSize(new java.awt.Dimension(57, 38));
        jPanel7.add(addRemButtonsPanel, java.awt.BorderLayout.CENTER);

        jLabel6.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel7.add(jLabel6, java.awt.BorderLayout.NORTH);

        jLabel7.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel7.add(jLabel7, java.awt.BorderLayout.SOUTH);

        jLabel8.setPreferredSize(new java.awt.Dimension(5, 0));
        jPanel7.add(jLabel8, java.awt.BorderLayout.EAST);

        jLabel9.setPreferredSize(new java.awt.Dimension(5, 0));
        jPanel7.add(jLabel9, java.awt.BorderLayout.WEST);

        jPanel3.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setMinimumSize(new java.awt.Dimension(149, 150));
        jPanel8.setPreferredSize(new java.awt.Dimension(145, 127));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jPanel9.setLayout(new java.awt.BorderLayout(0, 3));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 24));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("V");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel10.setPreferredSize(new java.awt.Dimension(12, 50));
        jPanel9.add(jLabel10, java.awt.BorderLayout.NORTH);

        cbEsq.setBackground(new java.awt.Color(255, 255, 204));
        cbEsq.setFont(new java.awt.Font("Tahoma", 0, 18));
        jPanel9.add(cbEsq, java.awt.BorderLayout.CENTER);

        jLabel13.setPreferredSize(new java.awt.Dimension(40, 35));
        jPanel9.add(jLabel13, java.awt.BorderLayout.SOUTH);

        jLabel15.setPreferredSize(new java.awt.Dimension(10, 0));
        jPanel9.add(jLabel15, java.awt.BorderLayout.WEST);

        jPanel8.add(jPanel9);

        jPanel10.setLayout(new java.awt.BorderLayout());
        jPanel8.add(jPanel10);

        fExpres.setPreferredSize(new java.awt.Dimension(92, 100));
        fExpres.setLayout(new java.awt.BorderLayout(0, 3));
        fExpres.add(formaSentencial, java.awt.BorderLayout.CENTER);

        jPanel8.add(fExpres);

        jPanel3.add(jPanel8, java.awt.BorderLayout.CENTER);

        jLabel16.setPreferredSize(new java.awt.Dimension(3, 0));
        jPanel3.add(jLabel16, java.awt.BorderLayout.WEST);

        jPanel1.add(jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(420, 95));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Legenda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 153))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel5.setLayout(new java.awt.GridLayout(4, 0));

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel14.setBackground(new java.awt.Color(255, 255, 204));
        jPanel11.add(jPanel14);

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel17.setText("Símb. Não-Terminal");
        jPanel11.add(jLabel17);

        jPanel5.add(jPanel11);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel15.setBackground(new java.awt.Color(255, 204, 204));
        jPanel12.add(jPanel15);

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel18.setText("Símb. Term. e Não-Term.");
        jPanel12.add(jLabel18);

        jPanel5.add(jPanel12);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel16.setBackground(new java.awt.Color(204, 255, 204));
        jPanel13.add(jPanel16);

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel19.setText("Símbolo Inicial");
        jPanel13.add(jLabel19);

        jPanel5.add(jPanel13);

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 10));
        jLabel20.setForeground(new java.awt.Color(255, 0, 51));
        jLabel20.setText("OBS: ");
        jPanel17.add(jLabel20);

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel21.setText("A Regra DEVE estar na FNC.");
        jPanel17.add(jLabel21);

        jPanel5.add(jPanel17);

        jPanel4.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("S");
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 44));
        jPanel6.add(jLabel3);

        cbSimbIni.setBackground(new java.awt.Color(204, 255, 204));
        cbSimbIni.setFont(new java.awt.Font("Tahoma", 0, 36));
        cbSimbIni.setToolTipText("Símbolo Inicial");
        cbSimbIni.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanel6.add(cbSimbIni);

        jPanel4.add(jPanel6);

        jPanel1.add(jPanel4);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Regras de Produção");
        jLabel1.setPreferredSize(new java.awt.Dimension(34, 50));
        jPanel2.add(jLabel1, java.awt.BorderLayout.NORTH);

        jLabel2.setPreferredSize(new java.awt.Dimension(5, 14));
        jPanel2.add(jLabel2, java.awt.BorderLayout.EAST);

        listRProd.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listRProd);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents
    
    private void posInitComponents() {
         this.addRemButtonsPanel.getBAdd().addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                addAction(null, null);
            }
        });
         this.addRemButtonsPanel.getBRemove().addActionListener(
                 new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                rmvAction();
            }
        });
        
        this.listRProd.setListData(rpsPanel);
        this.listRProd.setCellRenderer(new ListCellRenderer() {
            @Override
            public Component getListCellRendererComponent
                    (JList list, Object value, int index, 
                    boolean isSelected,boolean cellHasFocus) {
                Component comp = (Component)value;
                comp.setBackground(isSelected ? Color.LIGHT_GRAY : Color.white);
                //comp.setForeground(isSelected ? Color.LIGHT_GRAY : Color.black);
                return comp;
            }
       });
    }
    
    private void addAction(SimboloString sLadEsq, List<SimboloString> sLadDir) {
        List<SimboloString> ladoDireito = null;
        Object sNTerm = null; 
        if(sLadEsq==null) { // transicao inserida pelo usuário
            sNTerm = this.cbEsq.getSelectedItem();
            ladoDireito = formaSentencial.getSequencia();
            
        } else { // Caso os valores vem de um arquivo
            sNTerm = sLadEsq.getNome();
            ladoDireito = sLadDir;
        }
        
        int tam = ladoDireito.size();
        if(sNTerm!=null) {
            RegraProducao regProd = new RegraProducao();
            regProd.setSimbLEsq(new SimboloString(sNTerm.toString()));
            regProd.setSimbLDireito(ladoDireito);
            if (getProducoes().contains(regProd)) return;
            
            final JPanel rp = new JPanel();
            rp.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
            rp.setBackground(listRProd.getBackground());
            rp.add(new JLabel(sNTerm.toString()));
            rp.add(new JLabel(" -> "));
            if (tam==0) {
                rp.add(new JLabel(GLC.LAMBDA.getNome()));
            } else {
                Color foreground = new Color(242, 64, 37);
                for (SimboloString s : ladoDireito) {
                    JLabel l = new JLabel(s.getNome());
                    foreground = new Color(foreground.getRGB()^0x00FFFFFF);
                    l.setForeground(foreground);
                    rp.add(l);
                }
            }
            rpsPanel.add(rp);
            listRProd.updateUI();
            formaSentencial.limparSequencia();
            formaSentencial.updateUI();
        }
    }
    
    private void rmvAction() {
        if (listRProd.getSelectedIndex() < 0) return;
        rpsPanel.remove(listRProd.getSelectedIndex());
        listRProd.updateUI();
    }
    
    public FormaSentencial getFormaSentencial() {
        return formaSentencial;
    }
    
     /**
     * Observa o add e remove dos simbolos terminais e nao terminais
     * caso o simbolo nao contenha na regra de producao, a regra e removida.
     */
    void removeSimbolo(SimboloString s) {
        // verifica as regras de producao
        String sNome = s.getNome();
       for(int rpi = 0; rpi < rpsPanel.size(); rpi++) {
           JPanel rp = rpsPanel.get(rpi);
           Component comps[] = rp.getComponents();
           if (((JLabel)comps[0]).getText().equals(sNome)) {
               rpsPanel.remove(rpi); rpi--;
               continue;
           }
           
           for (int i = 2; i < comps.length; i++) {
               if (((JLabel)comps[i]).getText().equals(s.getNome())) {
                   rpsPanel.remove(rpi); rpi--;
                   break;
               }
           }
       }
       listRProd.updateUI();
       
       // se for um nao terminal, verifica os simbolos iniciais
       if(s.getNome().equals(s.getNome().toUpperCase()))
           this.cbSimbIni.removeItem(s.getNome());
       
        this.getFormaSentencial().removeSimbolo(s);
    }
 
     private Matcher getMatcher(String str) {
        String regex = "(.+) -> (.+)";       
        
        return Pattern.compile(regex).matcher(str);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.uem.din.yandre.sctmf.view.components.AddRemButtonsPanel addRemButtonsPanel;
    private javax.swing.JComboBox cbEsq;
    private javax.swing.JComboBox cbSimbIni;
    private javax.swing.JPanel fExpres;
    private br.uem.din.yandre.sctmf.view.modelos_formais.ling_liv_contex.glc.FormaSentencial formaSentencial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listRProd;
    // End of variables declaration//GEN-END:variables
    
}
