/*
 * ValSeqGLC.java
 *
 * Created on 8 de Agosto de 2007, 08:57
 */

package br.uem.din.yandre.sctmf.view.modelos_formais.ling_liv_contex.glc;

import br.uem.din.yandre.sctmf.model.pojo.GLC;
import br.uem.din.yandre.sctmf.model.pojo.ModeloFormal;
import br.uem.din.yandre.sctmf.model.pojo.RegraProducao;
import br.uem.din.yandre.sctmf.model.pojo.SimboloString;
import br.uem.din.yandre.sctmf.model.services.ValidaSequencia;
import br.uem.din.yandre.sctmf.model.services.transformacoes.GLC2FNC;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author  rafael2009_00
 */
public class ValSeqGLC extends javax.swing.JPanel {
    
    private GlcGUI gui;
    
    /** Creates new form ValSeqGLC */
    public ValSeqGLC(GlcGUI gui) {
        this.gui = gui;
        initComponents();
        posInitComponents();
    }
    
    void observer(GLC glc) {
        
        formaSentencial.removeTodosSimbolos();
        for (SimboloString s : glc.getSimbTerm()) 
            formaSentencial.adicionaSimbolo(s);
        
        this.aInfor.setText("");
         
        this.aInfor.append(
                "G = V, T, P, S\n");
                
        StringBuffer sb = new StringBuffer();        
        sb.append("V = {");  // Add Simbolos Nao-Terminais
        for(SimboloString s : glc.getSimbNTerm())
            sb.append(s.getNome()+", ");                
        sb = this.formataSb(sb);
                
        sb.append("T = {");  // Add Simbolos Terminais
        for(SimboloString s : glc.getSimbTerm())
            sb.append(s.getNome()+", ");                
        sb = this.formataSb(sb);
                              
        SimboloString aux = glc.getSimbInicial();
        sb.append("S = ");
        if(aux!=null)
             sb.append(aux.getNome());        
        sb.append("\n");
        this.aInfor.append(sb.toString());
        
        sb = new StringBuffer("P = {");              
        int i = 1;
        for(RegraProducao rp : glc.getRegrasProducao()) {
             sb.append("\n")           // pula a linha
             .append(i+") ")
             .append(rp.getSimbLEsq().getNome())
             .append(" -> ");             
             for(SimboloString x : rp.getSimbLDireito())
                 sb.append(x.getNome());
             
             i++;
        }
        sb.append(glc.getRegrasProducao().size()>0?"\n      }":"}");
        
        this.aInfor.append(sb.toString());
    }
    
    public StringBuffer formataSb(StringBuffer sb) {
        int size = sb.length();        
        if(size>6)
            sb.delete(size-2,size);
            
        sb.append("}\n");  
        aInfor.append(sb.toString());
        sb = new StringBuffer();
        
        return sb;
                    
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        aInfor = new javax.swing.JTextArea();
        pWorker = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pTeste = new javax.swing.JPanel();
        formaSentencial = new br.uem.din.yandre.sctmf.view.modelos_formais.ling_liv_contex.glc.FormaSentencial();
        jPanel8 = new javax.swing.JPanel();
        bValidar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setPreferredSize(new java.awt.Dimension(0, 10));
        add(jLabel1, java.awt.BorderLayout.NORTH);

        aInfor.setBackground(new java.awt.Color(204, 255, 204));
        aInfor.setEditable(false);
        aInfor.setRows(5);
        jScrollPane.setViewportView(aInfor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        pWorker.setLayout(new java.awt.BorderLayout());

        jPanel6.setMinimumSize(new java.awt.Dimension(200, 40));
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel2.setText("Entre com a seqüência a ser testada");
        jPanel6.add(jLabel2);

        pWorker.add(jPanel6, java.awt.BorderLayout.NORTH);

        pTeste.setLayout(new java.awt.BorderLayout());

        formaSentencial.setPreferredSize(new java.awt.Dimension(120, 115));
        pTeste.add(formaSentencial, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        bValidar.setText("Analisar a Seqüência");
        bValidar.setPreferredSize(new java.awt.Dimension(180, 40));
        jPanel8.add(bValidar);

        pTeste.add(jPanel8, java.awt.BorderLayout.SOUTH);

        pWorker.add(pTeste, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(pWorker);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void posInitComponents() { 
        this.jSplitPane1.setDividerLocation(115);
       
        this.bValidar.addActionListener(
            new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                validarSequencia();
            }
        });   
        
    }
    
    public FormaSentencial getFormaSentencial() {
        return formaSentencial;
    }

    private void validarSequencia() {
        GLC2FNC transf = new GLC2FNC();
        transf.setModeloFormalOrigem((GLC)this.gui.getModeloFormal());
        ValidaSequencia.getInstance().valida(
                (ModeloFormal)transf.transformar(),
                this.formaSentencial.getSequencia());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aInfor;
    private javax.swing.JButton bValidar;
    private br.uem.din.yandre.sctmf.view.modelos_formais.ling_liv_contex.glc.FormaSentencial formaSentencial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pTeste;
    private javax.swing.JPanel pWorker;
    // End of variables declaration//GEN-END:variables
    
}
