/*
 * CadFunTransGLC.java
 *
 * Created on 7 de Agosto de 2007, 09:13
 */

package cassolato.rafael.sctmf.view.modelos_formais.ling_liv_contex.glc;

/**
 *
 * @author  rafael2009_00
 */
public class CadFunTransGLC extends javax.swing.JPanel {
    
    /**
     * Creates new form CadFunTransGLC
     */
    public CadFunTransGLC() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        addRemButtonsPanel1 = new cassolato.rafael.sctmf.view.components.AddRemButtonsPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cbEsq = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        fExpres = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        genericJList1 = new cassolato.rafael.sctmf.view.components.GenericJList();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMinimumSize(new java.awt.Dimension(280, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(280, 10));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel4.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel3.add(jLabel4, java.awt.BorderLayout.NORTH);

        jLabel5.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel3.add(jLabel5, java.awt.BorderLayout.SOUTH);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel7.add(addRemButtonsPanel1, java.awt.BorderLayout.CENTER);

        jLabel6.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel7.add(jLabel6, java.awt.BorderLayout.NORTH);

        jLabel7.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel7.add(jLabel7, java.awt.BorderLayout.SOUTH);

        jLabel8.setPreferredSize(new java.awt.Dimension(5, 0));
        jPanel7.add(jLabel8, java.awt.BorderLayout.EAST);

        jLabel9.setPreferredSize(new java.awt.Dimension(5, 0));
        jPanel7.add(jLabel9, java.awt.BorderLayout.WEST);

        jPanel3.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.X_AXIS));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new java.awt.BorderLayout(0, 3));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 24));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("V");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel10.setPreferredSize(new java.awt.Dimension(12, 50));
        jPanel9.add(jLabel10, java.awt.BorderLayout.NORTH);

        cbEsq.setFont(new java.awt.Font("Tahoma", 0, 18));
        cbEsq.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));
        jPanel9.add(cbEsq, java.awt.BorderLayout.CENTER);

        jLabel13.setPreferredSize(new java.awt.Dimension(40, 35));
        jPanel9.add(jLabel13, java.awt.BorderLayout.SOUTH);

        jLabel15.setPreferredSize(new java.awt.Dimension(10, 0));
        jPanel9.add(jLabel15, java.awt.BorderLayout.WEST);

        jPanel8.add(jPanel9);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 28));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel12.setPreferredSize(new java.awt.Dimension(39, 50));
        jLabel12.setText("\u2192");
        jPanel10.add(jLabel12, java.awt.BorderLayout.NORTH);

        jPanel8.add(jPanel10);

        fExpres.setLayout(new java.awt.BorderLayout(0, 3));

        fExpres.setPreferredSize(new java.awt.Dimension(92, 100));
        jLabel11.setFont(new java.awt.Font("Verdana", 0, 24));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("B");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel11.setPreferredSize(new java.awt.Dimension(12, 50));
        fExpres.add(jLabel11, java.awt.BorderLayout.NORTH);

        jLabel14.setPreferredSize(new java.awt.Dimension(40, 35));
        fExpres.add(jLabel14, java.awt.BorderLayout.SOUTH);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18));
        fExpres.add(jTextField1, java.awt.BorderLayout.CENTER);

        jPanel8.add(fExpres);

        jPanel3.add(jPanel8, java.awt.BorderLayout.CENTER);

        jLabel16.setPreferredSize(new java.awt.Dimension(3, 0));
        jPanel3.add(jLabel16, java.awt.BorderLayout.WEST);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        jPanel5.setLayout(new java.awt.GridLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Legenda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 153)));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel4.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("S");
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 44));
        jPanel6.add(jLabel3);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 36));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "A", "B" }));
        jComboBox1.setToolTipText("S\u00edmbolo Inicial");
        jComboBox1.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanel6.add(jComboBox1);

        jPanel4.add(jPanel6);

        jPanel1.add(jPanel4);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Regras de Produ\u00e7\u00e3o");
        jLabel1.setPreferredSize(new java.awt.Dimension(34, 50));
        jPanel2.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel2.add(genericJList1, java.awt.BorderLayout.CENTER);

        jLabel2.setPreferredSize(new java.awt.Dimension(5, 14));
        jPanel2.add(jLabel2, java.awt.BorderLayout.EAST);

        add(jPanel2);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cassolato.rafael.sctmf.view.components.AddRemButtonsPanel addRemButtonsPanel1;
    private javax.swing.JComboBox cbEsq;
    private javax.swing.JPanel fExpres;
    private cassolato.rafael.sctmf.view.components.GenericJList genericJList1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
