/*
 * CadFunTransGLC.java
 *
 * Created on 7 de Agosto de 2007, 09:13
 */

package cassolato.rafael.sctmf.view.modelos_formais.ling_liv_contex.glc;

import cassolato.rafael.sctmf.model.pojo.RegraProducao;
import cassolato.rafael.sctmf.model.pojo.Simbolo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author  rafael2009_00
 */
public class CadFunTransGLC extends javax.swing.JPanel {
    private Set<Simbolo> simbTerm = new LinkedHashSet<Simbolo>();
    private Set<Simbolo> simbNTerm = new LinkedHashSet<Simbolo>();
    
    /**
     * Creates new form CadFunTransGLC
     */
    public CadFunTransGLC() {
        initComponents();
        posInitComponents();
    }
    
    void observer(Set<Simbolo> simbTerm, Set<Simbolo> simbNTerm) {
       this.simbTerm = simbTerm;
       this.simbNTerm = simbNTerm;
       
       // guarda o antigo simbolo inicial
       Object o = cbSimbIni.getSelectedItem(); 
              
       cbEsq.removeAllItems();
       cbSimbIni.removeAllItems();
       for(Simbolo s : simbNTerm) {
           cbEsq.addItem(s.getNome());
           cbSimbIni.addItem(s.getNome());
       }
       
       // Seleciona novamente o simbolo inicial
       if(o!=null) {
           char item = (Character)o;
           for(Simbolo s : simbNTerm)
               if(s.getNome().equals(item))
                   cbSimbIni.setSelectedItem(item);
       }
    }
    
    Set<RegraProducao> getProducoes() {
        Set<RegraProducao> producoes = new LinkedHashSet<RegraProducao>();
        for(Object o : this.listRProd.getAllItens()) {
            Matcher m = this.getMatcher(o.toString());
            RegraProducao rp = new RegraProducao();
            if(m.find()) {                
                rp.setSimbLEsq(new Simbolo(m.group(1).charAt(0)));
                
                List<Simbolo> sLDireito = new ArrayList<Simbolo>();
                for(char c : m.group(2).toCharArray())
                    sLDireito.add(new Simbolo(c));
                
                rp.setSimbLDireito(sLDireito);
                
                producoes.add(rp);
            }
            
        }
        
        return producoes;
    }
    
    void setProducoes(Set<RegraProducao> regrasProducao) {
        listRProd.removeAllItens();
        for(RegraProducao rp : regrasProducao)
            this.addAction(rp.getSimbLEsq(), rp.getSimbLDireito());
        
    }
    
    Simbolo getSimboloInicial() {
        Object o = cbSimbIni.getSelectedItem();        
        return (o!=null)?new Simbolo(o.toString().charAt(0)):null;
    }
    
     void setSimbInicial(Simbolo simbolo) {
        this.cbSimbIni.setSelectedItem(simbolo.getNome());
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        addRemButtonsPanel = new cassolato.rafael.sctmf.view.components.AddRemButtonsPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cbEsq = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        fExpres = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fLadoDireito = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbSimbIni = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listRProd = new cassolato.rafael.sctmf.view.components.GenericJList();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setMinimumSize(new java.awt.Dimension(280, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(280, 10));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel4.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel3.add(jLabel4, java.awt.BorderLayout.NORTH);

        jLabel5.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel3.add(jLabel5, java.awt.BorderLayout.SOUTH);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel7.add(addRemButtonsPanel, java.awt.BorderLayout.CENTER);

        jLabel6.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel7.add(jLabel6, java.awt.BorderLayout.NORTH);

        jLabel7.setPreferredSize(new java.awt.Dimension(0, 10));
        jPanel7.add(jLabel7, java.awt.BorderLayout.SOUTH);

        jLabel8.setPreferredSize(new java.awt.Dimension(5, 0));
        jPanel7.add(jLabel8, java.awt.BorderLayout.EAST);

        jLabel9.setPreferredSize(new java.awt.Dimension(5, 0));
        jPanel7.add(jLabel9, java.awt.BorderLayout.WEST);

        jPanel3.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.X_AXIS));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new java.awt.BorderLayout(0, 3));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 24));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("V");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel10.setPreferredSize(new java.awt.Dimension(12, 50));
        jPanel9.add(jLabel10, java.awt.BorderLayout.NORTH);

        cbEsq.setBackground(new java.awt.Color(255, 255, 204));
        cbEsq.setFont(new java.awt.Font("Tahoma", 0, 18));
        jPanel9.add(cbEsq, java.awt.BorderLayout.CENTER);

        jLabel13.setPreferredSize(new java.awt.Dimension(40, 35));
        jPanel9.add(jLabel13, java.awt.BorderLayout.SOUTH);

        jLabel15.setPreferredSize(new java.awt.Dimension(10, 0));
        jPanel9.add(jLabel15, java.awt.BorderLayout.WEST);

        jPanel8.add(jPanel9);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 28));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel12.setPreferredSize(new java.awt.Dimension(39, 50));
        jLabel12.setText("\u2192");
        jPanel10.add(jLabel12, java.awt.BorderLayout.NORTH);

        jPanel8.add(jPanel10);

        fExpres.setLayout(new java.awt.BorderLayout(0, 3));

        fExpres.setPreferredSize(new java.awt.Dimension(92, 100));
        jLabel11.setFont(new java.awt.Font("Verdana", 0, 24));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel11.setPreferredSize(new java.awt.Dimension(12, 50));
        jLabel11.setText("\u03B2");
        fExpres.add(jLabel11, java.awt.BorderLayout.NORTH);

        jLabel14.setPreferredSize(new java.awt.Dimension(40, 35));
        fExpres.add(jLabel14, java.awt.BorderLayout.SOUTH);

        fLadoDireito.setBackground(new java.awt.Color(255, 204, 204));
        fLadoDireito.setFont(new java.awt.Font("Tahoma", 0, 18));
        fExpres.add(fLadoDireito, java.awt.BorderLayout.CENTER);

        jPanel8.add(fExpres);

        jPanel3.add(jPanel8, java.awt.BorderLayout.CENTER);

        jLabel16.setPreferredSize(new java.awt.Dimension(3, 0));
        jPanel3.add(jLabel16, java.awt.BorderLayout.WEST);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        jPanel5.setLayout(new java.awt.GridLayout(3, 0));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Legenda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 0, 153)));
        jPanel5.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel14.setBackground(new java.awt.Color(255, 255, 204));
        jPanel11.add(jPanel14);

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel17.setText("S\u00edmb. N\u00e3o-Terminal");
        jPanel11.add(jLabel17);

        jPanel5.add(jPanel11);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel15.setBackground(new java.awt.Color(255, 204, 204));
        jPanel12.add(jPanel15);

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel18.setText("S\u00edmb. Term. e N\u00e3o-Term.");
        jPanel12.add(jLabel18);

        jPanel5.add(jPanel12);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel16.setBackground(new java.awt.Color(204, 255, 204));
        jPanel13.add(jPanel16);

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel19.setText("S\u00edmbolo Inicial");
        jPanel13.add(jLabel19);

        jPanel5.add(jPanel13);

        jPanel4.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("S");
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 44));
        jPanel6.add(jLabel3);

        cbSimbIni.setBackground(new java.awt.Color(204, 255, 204));
        cbSimbIni.setFont(new java.awt.Font("Tahoma", 0, 36));
        cbSimbIni.setToolTipText("S\u00edmbolo Inicial");
        cbSimbIni.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanel6.add(cbSimbIni);

        jPanel4.add(jPanel6);

        jPanel1.add(jPanel4);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Regras de Produ\u00e7\u00e3o");
        jLabel1.setPreferredSize(new java.awt.Dimension(34, 50));
        jPanel2.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel2.add(listRProd, java.awt.BorderLayout.CENTER);

        jLabel2.setPreferredSize(new java.awt.Dimension(5, 14));
        jPanel2.add(jLabel2, java.awt.BorderLayout.EAST);

        add(jPanel2);

    }// </editor-fold>//GEN-END:initComponents
    
    private void posInitComponents() {
         this.addRemButtonsPanel.getBAdd().addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae) {
                addAction(null, null);
            }
        });
        
        this.addRemButtonsPanel.getBRemove().addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae) {
                removeAction();
            }
        });
                
    }
    
    private void addAction(Simbolo sLadEsq, List<Simbolo> sLadDir) {
        String ladoDireito = "";
        Object sNTerm = null; 
        if(sLadEsq==null) { // transicao inserida pelo usuário
            sNTerm = this.cbEsq.getSelectedItem();
            ladoDireito = fLadoDireito.getText();    
            
        }else { // Caso os valores vem de um arquivo
            sNTerm = sLadEsq.getNome();
            for(Simbolo s : sLadDir)
                ladoDireito += s.getNome();
        }
        
        int tam = ladoDireito.length();
        if(sNTerm!=null&&tam>0) {            
            if(this.isFNC(ladoDireito)) {
                // verifica se os simbolos digitados foram cadastrados no 
                // alfabeto
                boolean status = false;
                if(tam==1) {
                    char c = ladoDireito.charAt(0);
                    for(Simbolo s : simbTerm)
                        if(s.getNome()==c) {
                            status = true;
                            break;
                        }
                }else  // tam==2                    
                    for(int i=0;i<2;i++) {
                        status = false;
                        char c = ladoDireito.charAt(i);
                        for(Simbolo s : simbNTerm) 
                            if(s.getNome()==c) { 
                                status = true;
                                break;
                            }                        
                            
                        if(!status) break;
                        
                    }                
                        
                if(!status)
                    javax.swing.JOptionPane.showMessageDialog(null, 
                        "Símbolos não Cadastrados" , "Atenção", 
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                else                
                    this.listRProd.addItem(
                        sNTerm.toString()+" -> "+ladoDireito);    
            }            
            else
                javax.swing.JOptionPane.showMessageDialog(null, 
                        "Lado direito da expressão não está \n" +
                        "na Forma Normal de Chomsky", "Atenção - FNC", 
                        javax.swing.JOptionPane.WARNING_MESSAGE);
        }        
        
    }
    
    private void removeAction() {
        this.listRProd.removeItens();
    }
    
    /**
     * Verifica se o lado direito da regra de produção está<br>
     * na forma normal de chomsky
     */
    private boolean isFNC(String value) {
        int tam = value.length();
        if(tam>2) return false;
        if(tam==1) {
            if(Character.isLowerCase(value.charAt(0))) // A -> a
                return true;
            else return false;
        
        } else if(Character.isUpperCase(value.charAt(0))&&
                Character.isUpperCase(value.charAt(1))) // A -> BC
            return true;
        
        else return false;
    }
    
     /**
     * Observa o add e remove dos simbolos terminais e nao terminais
     * caso o simbolo nao contenha na regra de producao, a regra e removida.
     */
    void removeSimbolo(Simbolo s) {
        // verifica as regras de producao
       for(Object o : this.listRProd.getAllItens()) {           
           if(o.toString().contains(Character.toString(s.getNome())))
               this.listRProd.removeItem(o);
       }
       
       // se for um nao terminal, verifica os simbolos iniciais
       if(Character.isUpperCase(s.getNome()))
           this.cbSimbIni.removeItem(s.getNome());
       
    }
 
     private Matcher getMatcher(String str) {
        String regex = "(.+) -> (.+)";
        
        return Pattern.compile(regex).matcher(str);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cassolato.rafael.sctmf.view.components.AddRemButtonsPanel addRemButtonsPanel;
    private javax.swing.JComboBox cbEsq;
    private javax.swing.JComboBox cbSimbIni;
    private javax.swing.JPanel fExpres;
    private javax.swing.JTextField fLadoDireito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private cassolato.rafael.sctmf.view.components.GenericJList listRProd;
    // End of variables declaration//GEN-END:variables
    
}
