/*
 * CadFTransMT.java
 *
 * Created on 23 de Agosto de 2007, 09:14
 */

package cassolato.rafael.sctmf.view.modelos_formais.ling_enum_rec.mt;

/**
 *
 * @author  rafael2009_00
 */
public class CadFTransMT extends javax.swing.JPanel {
    
    /** Creates new form CadFTransMT */
    public CadFTransMT() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        cbEstOri = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        fSimDestPilha1 = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        cbEstDest = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        fSimDestPilha = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbBasePilha = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        bAddSimIniFitaEsq = new javax.swing.JButton();
        bAddSimbBrancEsq = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel58 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jPanel59 = new javax.swing.JPanel();
        jPanel60 = new javax.swing.JPanel();
        jPanel61 = new javax.swing.JPanel();
        bAddSimIniFitaDir = new javax.swing.JButton();
        bAddSimbBrancDir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel62 = new javax.swing.JPanel();
        jPanel63 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        addRemTran = new cassolato.rafael.sctmf.view.components.AddRemButtonsPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        listTrans = new cassolato.rafael.sctmf.view.components.GenericJList();

        setLayout(new java.awt.BorderLayout());

        jLabel17.setPreferredSize(new java.awt.Dimension(40, 10));
        add(jLabel17, java.awt.BorderLayout.NORTH);

        jLabel18.setPreferredSize(new java.awt.Dimension(5, 14));
        add(jLabel18, java.awt.BorderLayout.EAST);

        jLabel19.setPreferredSize(new java.awt.Dimension(40, 10));
        add(jLabel19, java.awt.BorderLayout.SOUTH);

        jLabel20.setText("  ");
        add(jLabel20, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.X_AXIS));

        jPanel10.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel10.setMaximumSize(new java.awt.Dimension(20, 60));
        jPanel10.setPreferredSize(new java.awt.Dimension(20, 60));
        jLabel22.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel22.setPreferredSize(new java.awt.Dimension(10, 30));
        jLabel22.setText("\u03B4:");
        jPanel10.add(jLabel22, java.awt.BorderLayout.NORTH);

        jPanel8.add(jPanel10);

        jPanel24.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel24.setOpaque(false);
        jPanel24.setPreferredSize(new java.awt.Dimension(25, 30));
        cbEstOri.setBackground(new java.awt.Color(204, 255, 204));
        cbEstOri.setToolTipText("Estado de Origem");
        jPanel24.add(cbEstOri, java.awt.BorderLayout.CENTER);

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("S");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel24.setPreferredSize(new java.awt.Dimension(20, 30));
        jPanel24.add(jLabel24, java.awt.BorderLayout.NORTH);

        jPanel8.add(jPanel24);

        jPanel25.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel25.setMaximumSize(new java.awt.Dimension(20, 60));
        jPanel25.setOpaque(false);
        jPanel25.setPreferredSize(new java.awt.Dimension(10, 60));
        jLabel28.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("x");
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel28.setPreferredSize(new java.awt.Dimension(20, 30));
        jPanel25.add(jLabel28, java.awt.BorderLayout.NORTH);

        jPanel8.add(jPanel25);

        jPanel26.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel26.setOpaque(false);
        jPanel26.setPreferredSize(new java.awt.Dimension(50, 30));
        jLabel34.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel34.setPreferredSize(new java.awt.Dimension(20, 30));
        jLabel34.setText("(\u03a3\u222AV\u222A{\u03B2,\u00A4})");
        jPanel26.add(jLabel34, java.awt.BorderLayout.NORTH);

        fSimDestPilha1.setBackground(new java.awt.Color(255, 255, 204));
        fSimDestPilha1.setToolTipText("Entrada da Pilha");
        jPanel26.add(fSimDestPilha1, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel26);

        jPanel29.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel29.setPreferredSize(new java.awt.Dimension(10, 30));
        jLabel32.setFont(new java.awt.Font("Arial", 1, 15));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel32.setPreferredSize(new java.awt.Dimension(20, 30));
        jLabel32.setText("\u2192");
        jPanel29.add(jLabel32, java.awt.BorderLayout.NORTH);

        jPanel8.add(jPanel29);

        jPanel30.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel30.setOpaque(false);
        jPanel30.setPreferredSize(new java.awt.Dimension(35, 30));
        cbEstDest.setBackground(new java.awt.Color(204, 204, 255));
        cbEstDest.setToolTipText("Estado de Destino");
        jPanel30.add(cbEstDest, java.awt.BorderLayout.CENTER);

        jLabel33.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("S");
        jLabel33.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel33.setPreferredSize(new java.awt.Dimension(20, 30));
        jPanel30.add(jLabel33, java.awt.BorderLayout.NORTH);

        jPanel8.add(jPanel30);

        jPanel27.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel27.setMaximumSize(new java.awt.Dimension(20, 60));
        jPanel27.setPreferredSize(new java.awt.Dimension(10, 60));
        jLabel29.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("x");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel29.setPreferredSize(new java.awt.Dimension(20, 30));
        jPanel27.add(jLabel29, java.awt.BorderLayout.NORTH);

        jPanel8.add(jPanel27);

        jPanel32.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel32.setPreferredSize(new java.awt.Dimension(50, 30));
        fSimDestPilha.setBackground(new java.awt.Color(255, 204, 204));
        fSimDestPilha.setToolTipText("Entrada da Pilha");
        jPanel32.add(fSimDestPilha, java.awt.BorderLayout.CENTER);

        jLabel36.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel36.setPreferredSize(new java.awt.Dimension(20, 30));
        jLabel36.setText("(\u03a3\u222AV\u222A{\u03B2,\u00A4})");
        jPanel32.add(jLabel36, java.awt.BorderLayout.NORTH);

        jPanel8.add(jPanel32);

        jPanel31.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel31.setMaximumSize(new java.awt.Dimension(20, 60));
        jPanel31.setPreferredSize(new java.awt.Dimension(10, 60));
        jLabel30.setFont(new java.awt.Font("Verdana", 1, 12));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("x");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel30.setPreferredSize(new java.awt.Dimension(20, 30));
        jPanel31.add(jLabel30, java.awt.BorderLayout.NORTH);

        jPanel8.add(jPanel31);

        jPanel28.setLayout(new java.awt.BorderLayout(0, 2));

        jPanel28.setOpaque(false);
        jPanel28.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 8));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/media/StepBack16.gif")));
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel9.add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/media/StepForward16.gif")));
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel9.add(jLabel2);

        jPanel28.add(jPanel9, java.awt.BorderLayout.NORTH);

        cbBasePilha.setBackground(new java.awt.Color(200, 245, 240));
        cbBasePilha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "E", "D" }));
        cbBasePilha.setToolTipText("Sentido de Movimento(Esquerda/Direita)");
        jPanel28.add(cbBasePilha, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel28);

        jPanel3.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.X_AXIS));

        jPanel7.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel54.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel54.setMaximumSize(new java.awt.Dimension(20, 60));
        jPanel54.setPreferredSize(new java.awt.Dimension(20, 60));
        jLabel58.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel58.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel58.setPreferredSize(new java.awt.Dimension(10, 30));
        jLabel22.setText("\u03B4:");
        jPanel54.add(jLabel58, java.awt.BorderLayout.NORTH);

        jPanel7.add(jPanel54);

        jPanel55.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel55.setOpaque(false);
        jPanel55.setPreferredSize(new java.awt.Dimension(25, 30));
        jPanel7.add(jPanel55);

        jPanel56.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel56.setMaximumSize(new java.awt.Dimension(20, 60));
        jPanel56.setOpaque(false);
        jPanel56.setPreferredSize(new java.awt.Dimension(10, 60));
        jPanel7.add(jPanel56);

        jPanel57.setLayout(new java.awt.BorderLayout());

        jPanel57.setOpaque(false);
        jPanel57.setPreferredSize(new java.awt.Dimension(50, 30));
        bAddSimIniFitaEsq.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11));
        bAddSimIniFitaEsq.setPreferredSize(new java.awt.Dimension(40, 23));
        bAddSimIniFita.setText("\u00A4");
        bAddSimIniFitaEsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddSimIniFitaEsqActionPerformed(evt);
            }
        });

        jPanel57.add(bAddSimIniFitaEsq, java.awt.BorderLayout.EAST);

        bAddSimbBrancEsq.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10));
        bAddSimbBrancEsq.setPreferredSize(new java.awt.Dimension(40, 23));
        bAddSimbBranc.setText("\u03B2");
        bAddSimbBrancEsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddSimbBrancEsqActionPerformed(evt);
            }
        });

        jPanel57.add(bAddSimbBrancEsq, java.awt.BorderLayout.WEST);

        jLabel7.setPreferredSize(new java.awt.Dimension(34, 5));
        jPanel57.add(jLabel7, java.awt.BorderLayout.NORTH);

        jPanel7.add(jPanel57);

        jPanel58.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel58.setPreferredSize(new java.awt.Dimension(10, 30));
        jLabel62.setFont(new java.awt.Font("Arial", 1, 15));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel62.setPreferredSize(new java.awt.Dimension(20, 30));
        jLabel32.setText("\u2192");
        jPanel58.add(jLabel62, java.awt.BorderLayout.NORTH);

        jPanel7.add(jPanel58);

        jPanel59.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel59.setOpaque(false);
        jPanel59.setPreferredSize(new java.awt.Dimension(35, 30));
        jPanel7.add(jPanel59);

        jPanel60.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel60.setMaximumSize(new java.awt.Dimension(20, 60));
        jPanel60.setPreferredSize(new java.awt.Dimension(10, 60));
        jPanel7.add(jPanel60);

        jPanel61.setLayout(new java.awt.BorderLayout());

        jPanel61.setPreferredSize(new java.awt.Dimension(50, 30));
        bAddSimIniFitaDir.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11));
        bAddSimIniFitaDir.setPreferredSize(new java.awt.Dimension(40, 23));
        bAddSimIniFita.setText("\u00A4");
        jPanel61.add(bAddSimIniFitaDir, java.awt.BorderLayout.EAST);

        bAddSimbBrancDir.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10));
        bAddSimbBrancDir.setPreferredSize(new java.awt.Dimension(40, 23));
        bAddSimbBranc.setText("\u03B2");
        jPanel61.add(bAddSimbBrancDir, java.awt.BorderLayout.WEST);

        jLabel8.setPreferredSize(new java.awt.Dimension(34, 5));
        jPanel61.add(jLabel8, java.awt.BorderLayout.NORTH);

        jPanel7.add(jPanel61);

        jPanel62.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel62.setMaximumSize(new java.awt.Dimension(20, 60));
        jPanel62.setPreferredSize(new java.awt.Dimension(10, 60));
        jPanel7.add(jPanel62);

        jPanel63.setLayout(new java.awt.BorderLayout(0, 2));

        jPanel63.setOpaque(false);
        jPanel63.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel7.add(jPanel63);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jPanel4.setLayout(new java.awt.GridLayout(5, 0));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Legenda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 153)));
        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jPanel13.setBackground(new java.awt.Color(204, 255, 204));
        jPanel19.add(jPanel13);

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel23.setText("Estado de Origem");
        jPanel19.add(jLabel23);

        jPanel4.add(jPanel19);

        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jPanel14.setBackground(new java.awt.Color(255, 255, 204));
        jPanel20.add(jPanel14);

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel35.setText("S\u00edmbolo a ser lido");
        jPanel20.add(jLabel35);

        jPanel4.add(jPanel20);

        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jPanel23.setBackground(new java.awt.Color(204, 204, 255));
        jPanel22.add(jPanel23);

        jLabel39.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel39.setText("Estado de Destino");
        jPanel22.add(jLabel39);

        jPanel4.add(jPanel22);

        jPanel35.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jPanel36.setBackground(new java.awt.Color(255, 204, 204));
        jPanel35.add(jPanel36);

        jLabel40.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel40.setText("S\u00edmbolo a ser gravado");
        jPanel35.add(jLabel40);

        jPanel4.add(jPanel35);

        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jPanel15.setBackground(new java.awt.Color(200, 245, 240));
        jPanel21.add(jPanel15);

        jLabel38.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel38.setText("Sentido do Movimento");
        jPanel21.add(jLabel38);

        jPanel4.add(jPanel21);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel25.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel5.add(jLabel25, java.awt.BorderLayout.NORTH);

        jLabel26.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel5.add(jLabel26, java.awt.BorderLayout.SOUTH);

        jLabel27.setPreferredSize(new java.awt.Dimension(5, 14));
        jPanel5.add(jLabel27, java.awt.BorderLayout.WEST);

        jLabel31.setPreferredSize(new java.awt.Dimension(5, 14));
        jPanel5.add(jLabel31, java.awt.BorderLayout.EAST);

        jPanel5.add(addRemTran, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel21.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 12));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Transi\u00e7\u00f5es");
        jPanel6.add(jLabel21, java.awt.BorderLayout.NORTH);

        listTrans.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(listTrans, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void bAddSimIniFitaEsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddSimIniFitaEsqActionPerformed
// TODO adicione seu código de manipulação aqui:
    }//GEN-LAST:event_bAddSimIniFitaEsqActionPerformed

    private void bAddSimbBrancEsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddSimbBrancEsqActionPerformed
// TODO adicione seu código de manipulação aqui:
    }//GEN-LAST:event_bAddSimbBrancEsqActionPerformed
    
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private cassolato.rafael.sctmf.view.components.AddRemButtonsPanel addRemTran;
    private javax.swing.JButton bAddSimIniFitaDir;
    private javax.swing.JButton bAddSimIniFitaEsq;
    private javax.swing.JButton bAddSimbBrancDir;
    private javax.swing.JButton bAddSimbBrancEsq;
    private javax.swing.JComboBox cbBasePilha;
    private javax.swing.JComboBox cbBasePilha1;
    private javax.swing.JComboBox cbBasePilha2;
    private javax.swing.JComboBox cbEstDest;
    private javax.swing.JComboBox cbEstDest1;
    private javax.swing.JComboBox cbEstDest2;
    private javax.swing.JComboBox cbEstOri;
    private javax.swing.JComboBox cbEstOri1;
    private javax.swing.JComboBox cbEstOri2;
    private javax.swing.JTextField fSimDestPilha;
    private javax.swing.JTextField fSimDestPilha1;
    private javax.swing.JTextField fSimDestPilha2;
    private javax.swing.JTextField fSimDestPilha3;
    private javax.swing.JTextField fSimDestPilha4;
    private javax.swing.JTextField fSimDestPilha5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private cassolato.rafael.sctmf.view.components.GenericJList listTrans;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
