/*
 * MtGUI.java
 *
 * Created on 23 de Agosto de 2007, 08:13
 */

package cassolato.rafael.sctmf.view.modelos_formais.ling_enum_rec.mt;

import cassolato.rafael.sctmf.model.pojo.ModeloFormal;
import cassolato.rafael.sctmf.view.modelos_formais.ModeloFormalGUI;

/**
 *
 * @author  rafael2009_00
 */
public class MtGUI extends ModeloFormalGUI {
    
    private CadAlfMT cadAlf = new CadAlfMT();
    private CadEstMT cadEst = new CadEstMT();
    private CadFTransMT cadFTrans = new CadFTransMT();
    private ValSeqMT valSeq = new ValSeqMT();
    
    /** Creates new form MtGUI */
    public MtGUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pCadAlf = new javax.swing.JPanel();
        pCadEst = new javax.swing.JPanel();
        pCadFTrans = new javax.swing.JPanel();
        pValSeq = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pCadAlf.setLayout(new java.awt.GridLayout());

        pCadAlf.add(this.cadAlf);
        jTabbedPane1.addTab("Alfabetos", pCadAlf);

        pCadEst.setLayout(new java.awt.GridLayout());

        pCadEst.add(this.cadEst);
        jTabbedPane1.addTab("Estados", pCadEst);

        pCadFTrans.setLayout(new java.awt.GridLayout());

        pCadFTrans.add(this.cadFTrans);
        jTabbedPane1.addTab("Transi\u00e7\u00f5es", pCadFTrans);

        pValSeq.setLayout(new java.awt.GridLayout());

        pValSeq.add(this.valSeq);
        jTabbedPane1.addTab("Valid. Sequ\u00eancia", pValSeq);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    public void setModeloFormal(ModeloFormal mf) {
    }

    public ModeloFormal getModeloFormal() {
        return null;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pCadAlf;
    private javax.swing.JPanel pCadEst;
    private javax.swing.JPanel pCadFTrans;
    private javax.swing.JPanel pValSeq;
    // End of variables declaration//GEN-END:variables
    
}
