/*
 * MtGUI.java
 *
 * Created on 23 de Agosto de 2007, 08:13
 */

package cassolato.rafael.sctmf.view.modelos_formais.ling_enum_rec.mt;

import cassolato.rafael.sctmf.model.pojo.Estado;
import cassolato.rafael.sctmf.model.pojo.MT;
import cassolato.rafael.sctmf.model.pojo.ModeloFormal;
import cassolato.rafael.sctmf.model.pojo.Simbolo;
import cassolato.rafael.sctmf.model.pojo.TransicaoMT;
import cassolato.rafael.sctmf.view.modelos_formais.ModeloFormalGUI;

/**
 *
 * @author  rafael2009_00
 */
public class MtGUI extends ModeloFormalGUI {
    
    private CadAlfMT cadAlf = new CadAlfMT(this);
    private CadEstMT cadEst = new CadEstMT(this);
    private CadFTransMT cadFTrans = new CadFTransMT(this);
    private ValSeqMT valSeq = new ValSeqMT(this);
    
    /** Creates new form MtGUI */
    public MtGUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        tpMT = new javax.swing.JTabbedPane();
        pCadAlf = new javax.swing.JPanel();
        pCadEst = new javax.swing.JPanel();
        pCadFTrans = new javax.swing.JPanel();
        pValSeq = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pCadAlf.setLayout(new java.awt.GridLayout(1, 0));

        pCadAlf.add(this.cadAlf);
        tpMT.addTab("Alfabetos", pCadAlf);

        pCadEst.setLayout(new java.awt.GridLayout(1, 0));

        pCadEst.add(this.cadEst);
        tpMT.addTab("Estados", pCadEst);

        pCadFTrans.setLayout(new java.awt.GridLayout(1, 0));

        pCadFTrans.add(this.cadFTrans);
        tpMT.addTab("Transi\u00e7\u00f5es", pCadFTrans);

        pValSeq.setLayout(new java.awt.GridLayout(1, 0));

        pValSeq.add(this.valSeq);
        pValSeq.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pValSeqComponentShown(evt);
            }
        });

        tpMT.addTab("Valid. Sequ\u00eancia", pValSeq);

        add(tpMT, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void pValSeqComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pValSeqComponentShown
        this.valSeq.observer((MT)this.getModeloFormal());
    }//GEN-LAST:event_pValSeqComponentShown

    public void setModeloFormal(ModeloFormal mf) {
        MT mt = (MT)mf;
        this.cadAlf.setSimbAfabeto(mt.getAlfabeto());
        this.cadAlf.setSimbAfabetoAux(mt.getAlfabetoAux());
        
        this.cadEst.setEstados(mt.getEstados());
        this.cadEst.setEstadoInicial(mt.getEstIni());
        this.cadEst.setEstadosFinais(mt.getEstFinais());
        
        this.cadFTrans.setTransicoes(mt.getTransicoes());
        
        this.tpMT.setSelectedIndex(0);
    }

    public ModeloFormal getModeloFormal() {
        MT mt = new MT();
        mt.setAlfabeto(this.cadAlf.getSimbAfabeto());
        mt.setAlfabetoAux(this.cadAlf.getSimbAfabetoAux());
        
        mt.setEstados(this.cadEst.getEstados());
        mt.setEstIni(this.cadEst.getEstadoInicial());
        mt.setEstFinais(this.cadEst.getEstadosFinais());
        
        mt.setTransicoes(this.cadFTrans.getTransicoes());
        
        return mt;
    }

    void addSimbolo(Simbolo simbolo, int cod) {
        this.cadFTrans.observer(simbolo, true, cod);
    }
    
    void removeSimbolo(Simbolo simbolo, int cod) {
        this.cadFTrans.observer(simbolo, false, cod);
    }
        
    void addEstado(Estado estado) {
        this.cadFTrans.observer(estado, true);
    }
    
    void removeEstado(Estado estado) {
        this.cadFTrans.observer(estado, false);
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pCadAlf;
    private javax.swing.JPanel pCadEst;
    private javax.swing.JPanel pCadFTrans;
    private javax.swing.JPanel pValSeq;
    private javax.swing.JTabbedPane tpMT;
    // End of variables declaration//GEN-END:variables
    
}
