/*
 * CadFunTransAfnd.java
 *
 * Created on 26 de Maio de 2007, 17:22
 */

package cassolato.rafael.sctmf.view.formalmodels.ling_regul.afnd;

import cassolato.rafael.sctmf.view.formalmodels.ling_regul.afd.CadFunTrans;

/**
 *
 * @author  Cassolato
 */
public class CadFunTransAfnd extends CadFunTrans {
    
    /** Creates new form BeanForm */
    public CadFunTransAfnd() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {

    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Metodo sobrescrito para permitir um estado origem<br>
     * e um simbolo, possam chegar a mais de um estado final<br>
     * caracteristica essa do AFND.
     *
     * @param String
     * @return boolean
     */
    protected boolean wayAdd(String transicao) {        
        return true;
    }
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    // Fim da declaração de variáveis//GEN-END:variables
    
}
