/*
 * AddRemButtonsPanel.java
 *
 * Created on 13 de Março de 2007, 13:52
 */

package view;

/**
 *
 * @author  rafael2009_00
 */
public class AddRemButtonsPanel extends javax.swing.JPanel {
    
    public static final int ADD = 1;
    public static final int REMOVE = 2;
    
    /** Creates new form AddRemButtonsPanel */
    public AddRemButtonsPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        bAdd = new javax.swing.JButton();
        bRemove = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(4, 0, 0, 12));

        add(jLabel1);

        bAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Add24.gif")));
        add(bAdd);

        bRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Remove24.gif")));
        add(bRemove);

    }// </editor-fold>//GEN-END:initComponents
    
    public javax.swing.JButton getButton(int codButton){
        return (codButton==ADD?this.bAdd:this.bRemove);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bRemove;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
