/*
 * GenericJList.java
 *
 * Created on 3 de Maio de 2007, 09:21
 */

package cassolato.rafael.sctmf.view.components;

import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.DefaultListModel;

/**
 *
 * @author  rafael2009_00
 */
public class GenericJList extends javax.swing.JScrollPane {
    
    private DefaultListModel dlm = new DefaultListModel();
    
    /** Creates new form BeanForm */
    public GenericJList() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jList = new javax.swing.JList();

        jList.setFont(new java.awt.Font("Verdana", 1, 14));
        jList.setModel(this.dlm);
        setViewportView(jList);

    }// </editor-fold>//GEN-END:initComponents
    
    public void removeItens() {        
        Object[] itens = this.jList.getSelectedValues();
        
        if(itens.length>0)
            for(int i=0;i<itens.length;i++)
                this.dlm.removeElement(itens[i]);
    }
    
    public void addItem(Character item) {
        if(!this.dlm.contains(item))
            this.dlm.addElement(item);
    }
    
    public void addItem(String item) {
        if(!this.dlm.contains(item))
            this.dlm.addElement(item);
    }
    
    public void removeAllItens() {
            this.dlm.removeAllElements();
    }
    
    public Collection<Object> getAllItens() {        
        Set<Object> itens = new LinkedHashSet<Object>();    
        int size = this.dlm.size();
        
        for(int i=0;i<size;i++)
            itens.add(this.dlm.getElementAt(i));
        
        return itens;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList;
    // End of variables declaration//GEN-END:variables
    
}
