/*
 * GenericJList.java
 *
 * Created on 3 de Maio de 2007, 09:21
 */

package cassolato.rafael.sctmf.view.components;

import javax.swing.DefaultListModel;

/**
 *
 * @author  rafael2009_00
 */
public class GenericJList extends javax.swing.JScrollPane {
    
    private DefaultListModel dlm = new DefaultListModel();
    
    /** Creates new form BeanForm */
    public GenericJList() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jList = new javax.swing.JList();

        jList.setFont(new java.awt.Font("Verdana", 1, 14));
        jList.setModel(this.dlm);
        setViewportView(jList);

    }// </editor-fold>//GEN-END:initComponents
    
    public DefaultListModel getListModel() {
        return this.dlm;
    }
    
    public void removeItens() {
        Object[] itens = this.jList.getSelectedValues();
        
        if(itens.length>0)
            for(int i=0;i<itens.length;i++)
                this.dlm.removeElement(itens[i]);
    }
    
    public void addItem(Character c) {
        if(!this.dlm.contains(c))
            this.dlm.addElement(c);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList;
    // End of variables declaration//GEN-END:variables
    
}
