/*
 * ValidaSequenciaGUI.java
 *
 * Created on 18 de Junho de 2007, 19:28
 */

package cassolato.rafael.sctmf.view.components;

import cassolato.rafael.sctmf.model.pojo.ModeloFormal;
import cassolato.rafael.sctmf.model.services.ValidaSequencia;
import cassolato.rafael.sctmf.model.services.Validacao;

/**
 *
 * @author  Cassolato
 */
public class ValidaSequenciaGUI extends javax.swing.JPanel {
    private Validacao valida = ValidaSequencia.getInstance();
    
    /**
     * Creates new form ValidaSequenciaGUI
     */
    public ValidaSequenciaGUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSplitPane = new javax.swing.JSplitPane();
        pDigSeq = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fSequencia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        bValidar = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        aInfor = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jLabel3.setPreferredSize(new java.awt.Dimension(34, 10));
        add(jLabel3, java.awt.BorderLayout.SOUTH);

        jLabel4.setPreferredSize(new java.awt.Dimension(10, 14));
        add(jLabel4, java.awt.BorderLayout.EAST);

        jLabel13.setPreferredSize(new java.awt.Dimension(10, 14));
        add(jLabel13, java.awt.BorderLayout.WEST);

        jSplitPane.setDividerLocation(105);
        pDigSeq.setLayout(new java.awt.GridLayout(3, 0));

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 30));

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 14));
        jLabel2.setText("Digite a seq\u00fc\u00eancia a ser testada");
        jPanel6.add(jLabel2);

        pDigSeq.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel9.setPreferredSize(new java.awt.Dimension(34, 10));
        jPanel7.add(jLabel9, java.awt.BorderLayout.NORTH);

        jLabel10.setPreferredSize(new java.awt.Dimension(34, 10));
        jPanel7.add(jLabel10, java.awt.BorderLayout.SOUTH);

        fSequencia.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 24));
        jPanel7.add(fSequencia, java.awt.BorderLayout.CENTER);

        jLabel11.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel7.add(jLabel11, java.awt.BorderLayout.EAST);

        jLabel12.setPreferredSize(new java.awt.Dimension(20, 14));
        jPanel7.add(jLabel12, java.awt.BorderLayout.WEST);

        pDigSeq.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        bValidar.setText("Analisar a Seq\u00fc\u00eancia");
        bValidar.setPreferredSize(new java.awt.Dimension(180, 40));
        jPanel8.add(bValidar);

        pDigSeq.add(jPanel8);

        jSplitPane.setRightComponent(pDigSeq);

        aInfor.setBackground(new java.awt.Color(204, 255, 204));
        aInfor.setEditable(false);
        aInfor.setRows(5);
        jScrollPane.setViewportView(aInfor);

        jSplitPane.setLeftComponent(jScrollPane);

        add(jSplitPane, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    public javax.swing.JButton getBValidar() {
        return this.bValidar;
    }
    
    public String getTextAInf() {
        return this.aInfor.getText();
    }
    
    public void setTextAInf(String t) {
        String text = this.aInfor.getText();
        this.aInfor.setText(text+t);
    }
    
    public String getSequencia() {
        return this.fSequencia.getText();
    }
    
    public void selectAllFSequencia() {
        this.fSequencia.selectAll();
        this.fSequencia.requestFocus(true);
    }
    
    public void setSplitPaneLocation(int location) {
        this.jSplitPane.setDividerLocation(location);
    }
    
    public StringBuffer formataSb(StringBuffer sb) {
        int size = sb.length();        
        if(size>6)
            sb.delete(size-2,size);
            
        sb.append("}\n");  
        aInfor.append(sb.toString());
        sb = new StringBuffer();
        
        return sb;
                    
    }
    
    public void validarSequencia(ModeloFormal mf, String sequencia) {
        this.valida.valida(mf, sequencia);
    }
    
    public void clearArea() {
        this.aInfor.setText("");
    }
        
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JTextArea aInfor;
    private javax.swing.JButton bValidar;
    private javax.swing.JTextField fSequencia;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JPanel pDigSeq;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
