/*
 * CadEstAFMV.java
 *
 * Created on 24 de Setembro de 2007, 20:25
 */

package br.uem.din.yandre.sctmf.view.modelos_formais.ling_regul.afmv;

import br.uem.din.yandre.sctmf.view.modelos_formais.ling_regul.afd.CadEstAFD;

/**
 *
 * @author  Cassolato
 */
public class CadEstAFMV extends CadEstAFD {
    
    /** Creates new form CadEstAFMV */
    public CadEstAFMV() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {

        
    }// </editor-fold>//GEN-END:initComponents
       
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    // Fim da declaração de variáveis//GEN-END:variables
    
}
